feat(postgres): document PostgreSQL performance tuning
bonitasoft/bonita-doc pull request #1058
Opened 2019-10-04 13:08 UTC by educhastenier

Closes [BR-250](https://bonitasoft.atlassian.net/browse/BR-250)

2019-10-04 14:01 UTC, pabloalonso requested changes
Describe a Prod ready infraestructure like the one used for our Audit.
Use these values (specially RAM) to set up proper values on shared_buffers and effective_cache_size

2019-10-16 13:37 UTC, baptistemesta requested changes
Great PR.
Only few things to change.
Also should we link to tools that can be used to help configuring that. e.g. a link to pgCluu

2019-10-16 13:37 UTC, baptistemesta commented on md/performance-tuning.md
> +In this example, we assume with have:
```suggestion
In this example, we assume you have:
```

2019-10-16 13:37 UTC, baptistemesta commented on md/performance-tuning.md
> +If you want to be able to **restore live PITR backup** of the database, ensure archiving is activated:
We could tell what is `PITR` or at least only write in parenthesis the meaning of the acronym)

2019-10-17 14:55 UTC, educhastenier commented
@baptistemesta Feel free to contribute. I don't know pgCluu of pgBadger enough to document them...

2019-10-17 16:05 UTC, educhastenier commented on md/performance-tuning.md
> +If you want to be able to **restore live PITR backup** of the database, ensure archiving is activated:
:heavy_check_mark: done

2019-10-18 14:06 UTC, baptistemesta commented
I think that's a great first step. I don't know either pgCluu enough.

2019-10-18 14:07 UTC, merged