doc(tableWidget) How use new properties for Table and Data table widget
bonitasoft/bonita-doc pull request #1106
Opened 2019-11-18 14:59 UTC by benjaminParisel

Covers [UID-205](https://bonitasoft.atlassian.net/browse/UID-205)

2019-11-18 15:07 UTC, pabloalonso approved these changes
LGTM

2019-11-19 10:11 UTC, jeromecambon requested changes

2019-11-19 10:11 UTC, jeromecambon commented on md/widgets.md
> +You can customize default display for zebra-styling or bordered. Here an example to explain you how to customize default zebra styling.
```suggestion
You can customize default display for zebra-striping or bordered. Here is an example to explain you how to customize default zebra styling. 
```

2019-11-19 10:11 UTC, jeromecambon commented on md/widgets.md
> +* Zebra-Striping to set a different background color on even and odd lines
```suggestion
* Zebra-striping to set a different background color on even and odd lines
```

2019-11-19 10:11 UTC, jeromecambon commented on md/widgets.md
> +This styling can be done in the theme.css file in Bonita Studio part to customize **all** the tables. You need to use this following css selector:
```suggestion
This styling can be done in the theme.css file in Bonita Studio part to customize **all** the tables. You need to use the following css selector: 
```

2019-11-19 10:11 UTC, jeromecambon commented on md/widgets.md
> +Note: In embedded Table widget documentation you can found an example for bordered custom style.
I think it would be better to put the example here as well, and avoid to refer to embedded doc.

2019-11-27 15:58 UTC, merged