Init release note for version 7.10.1
bonitasoft/bonita-doc pull request #1134
Opened 2020-01-27 16:35 UTC by benjaminParisel

2020-01-28 09:48 UTC, NathalieC requested changes

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +### Fixes in Bonita 7.10.1 (2020-02-06)
We usually add the maintenance versions bugs on top of the ".0" version in the release notes.
So this chapter needs to go right after the "bugs in documentation" chapter if there is one.

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +#### Fixes in Web/Portal component
We usually start with Engine, then Studio, then UI Designer and then Web.
Maybe you have changed it on purpose and this is fine.
If not, then I suggest we stick with the usual order.

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +* BS-15956 The CPU of the DB server spikes to 100% for 90 minutes due to Portal Admin -Start for- button
This one is engine and not Portal in Jira.
It is Resolved and not Done/Closed. Needs to be Done/Closed to be put in the release notes.

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +* BPO-205 BS-19366 - Error 500 when accessing BPM services page
BS-19366 is Resolved but is not Closed. It should be so we consider it as over. May be a push to do to Support since I think they need to close the resolved bugs they have opened.

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +* BPO-104 BS-19008 - CAS ticket persists in URL in portal after login
BS-19008 is Resolved but not Closed. It should be. Push to Support?

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +* BPO-256 BS-19383 - Redirection back to CAS when Authenticated CAS user not valid in Bonita tries to access Bonita
BS-19383 is not Closed either

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +* UID-74 Remove whitespace between title and option for RadioButton and Checklist widget
The bug title should be the description of the issue, or issue and then the suggestion for resolution, not the resolution alone.

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +* UID-218 Move gitIgnore files in temporary folder to make import possible when user checkout another branch
same here, need to describe the issue

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +* UID-113 Generated Form displayDescription Text widget doesn't honor 'interpret HTML' property
Is "honoring" really a technical term?

2020-01-28 09:48 UTC, NathalieC commented on md/release-notes.md
> +* UID-221 Enable page or form artifact import when reference exist in index.json metadata file
same. Title needs to describe the issue.

2020-01-28 09:49 UTC, NathalieC commented on md/release-notes.md
> +* UID-221 Enable page or form artifact import when reference exist in index.json metadata file
Review done on my side. Changes requested.

2020-01-28 09:52 UTC, abirembaut commented on md/release-notes.md
> +* BS-15956 The CPU of the DB server spikes to 100% for 90 minutes due to Portal Admin -Start for- button
moved

2020-02-03 09:20 UTC, NathalieC commented on md/release-notes.md
> +#### Fixes in Web/Portal component
This has been changed in 7.10. I've sorted them according to this new order.

2020-02-03 10:28 UTC, NathalieC commented on md/release-notes.md
> +* BS-15956 The CPU of the DB server spikes to 100% for 90 minutes due to Portal Admin -Start for- button
I've closed it in accordance with Poorav.

2020-02-03 10:28 UTC, NathalieC commented on md/release-notes.md
> +* BPO-205 BS-19366 - Error 500 when accessing BPM services page
Now closed.

2020-02-03 10:28 UTC, NathalieC commented on md/release-notes.md
> +* BPO-256 BS-19383 - Redirection back to CAS when Authenticated CAS user not valid in Bonita tries to access Bonita
closed

2020-02-03 10:29 UTC, NathalieC commented on md/release-notes.md
> +* BPO-104 BS-19008 - CAS ticket persists in URL in portal after login
closed

2020-02-03 10:37 UTC, NathalieC commented on md/release-notes.md
> +* UID-74 Remove whitespace between title and option for RadioButton and Checklist widget
fixed after discussion with Pablo / Benjamin

2020-02-03 10:37 UTC, NathalieC commented on md/release-notes.md
> +* UID-113 Generated Form displayDescription Text widget doesn't honor 'interpret HTML' property
I assume it is, since no change has occurred in the JIRa ticket name.

2020-02-03 10:38 UTC, NathalieC commented on md/release-notes.md
> +* UID-221 Enable page or form artifact import when reference exist in index.json metadata file
fixed after talking to Pablo / Benjamin.

2020-02-03 10:38 UTC, NathalieC approved these changes

2020-02-03 10:38 UTC, NathalieC commented on md/release-notes.md
> +* UID-218 Move gitIgnore files in temporary folder to make import possible when user checkout another branch
fixed

2020-02-06 15:04 UTC, merged