fix(migration): detail the Oracle version change
bonitasoft/bonita-doc pull request #1151
Opened 2020-02-04 09:06 UTC by jjargot

Elaborate on the Oracle version change needed before using the migration script to migrate to 7.9.0.
Indeed, many customer faced issues with final target versions.

Versions: 7.9, 7.10

2020-02-05 16:53 UTC, ugaston reviewed
Awesome!
Just a minor correction regarding the Oracle db version (I believe the supported versions are 12.2.0.x.y), a small addition to remind users to test the upgrade to Oracle 12.2.0.x.y went fine by having them check a 7.8.4 server can actually be started upon the upgraded database.

And a tiny general comment: your bullet points sometimes start with a lower case, and sometimes they do so with an upper case...

Cheers!

2020-02-05 16:53 UTC, ugaston commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +Bonita 7.9+ supports Oracle 12c (12.2.x.y) version: this is a requirement change.
```suggestion
Bonita 7.9+ supports Oracle 12c (12.2.0.x.y) version: this is a requirement change.
```

2020-02-05 16:53 UTC, ugaston commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +* upgrade the Oracle database server to the version 12c (it must be 12.2.x.y)
```suggestion
* upgrade the Oracle database server to the version 12c (it must be 12.2.0.x.y)
```

2020-02-05 16:53 UTC, ugaston commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +
### Check the Bonita 7.8.4 server starts with the Oracle database server 12c (12.2.0.x.y)

* Download and install a Bonita 7.8.4 server
* Setup the Bonita 7.8.4 server to use the Oracle 12c (12.2.0.x.y) database
* Request and install a temporary 7.8 license in the Bonita server
* Start the Bonita 7.8.4 server
* Check you can successfully log into the portal

2020-02-05 16:53 UTC, ugaston commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +* install target Tomcat application server with bonita
... Is it necessarily a Tomcat, in 7.9+?
I believe we could still have Wildfly in 7.9.x (however deprecated it may have been)...

2020-02-25 15:15 UTC, pabloalonso requested changes
We plan to support Oracle19c in 7.9 and 7.10 
https://github.com/bonitasoft/bonita-doc/pull/1155
This PR should be updated accordling

2020-02-27 13:25 UTC, jjargot commented
Thank you Pablo, we've added the Oracle 19c (19.3.0.0) information.

2020-03-06 13:39 UTC, baptistemesta commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +    :::
```suggestion
::: info
Note: If you are using MySQL, add `?allowMultiQueries=true` to the URL. For example,
`db.url=jdbc:mysql://localhost:3306/bonita_migration?allowMultiQueries=true`.  
Also, if you are migrating to Bonita 7.9+, you must upgrade your database server to MySQL 8.0, see [Migrating to Bonita 7.9+ using MySQL](#mysql8) specific procedure below.
:::
```

2020-03-06 16:40 UTC, marielle-spiteri reviewed
my review, please check

2020-03-06 16:40 UTC, marielle-spiteri commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +* Oracle 12c (12.2.0.x.y) : [Oracle Database 12.2.0.1 JDBC Driver & UCP Downloads](https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html)
```suggestion
* Oracle 12c (12.2.0.x.y) : Driver ojdbc8.jar [Oracle Database 12.2.0.1 JDBC Driver & UCP Downloads](https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html) ( make sure it is the official driver by checking the SHA1 Checksum: 60f439fd01536508df32658d0a416c49ac6f07fb )
```

2020-03-06 16:40 UTC, marielle-spiteri commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +**Beware**: two different jdbc driver jar files may share the same name (ojdbc8.jar for example).
```suggestion
**Beware**: two different jdbc driver jar files may share the same name (ojdbc8.jar).
```

2020-03-06 16:40 UTC, marielle-spiteri commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +* Oracle 19c (19.3.0.0) : [Oracle Database 19c (19.3) JDBC Driver & UCP Downloads](https://www.oracle.com/database/technologies/appdev/jdbc-ucp-19c-downloads.html)
```suggestion
* Oracle 19c (19.3.0.0) : Driver ojdbc8.jar [Oracle Database 19c (19.3) JDBC Driver & UCP Downloads](https://www.oracle.com/database/technologies/appdev/jdbc-ucp-19c-downloads.html) ( make sure it is the official driver by checking the SHA1 Checksum: 967c0b1a2d5b1435324de34a9b8018d294f8f47b )
```

2021-02-04 09:38 UTC, educhastenier commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +    If you use Oracle and are migrating from version 7.9.0 and higher, add the JDBC driver for your database to `bonita-migration/lib`. This is the same driver as you have installed in your web serve
Now, lib/ojdbc8-19.3.0.0.jar is provided with the migration tool.
Please update the documentation accordingly @jjargot . Thx.

2021-02-04 09:41 UTC, educhastenier commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +* Oracle 19c (19.3.0.0) : [Oracle Database 19c (19.3) JDBC Driver & UCP Downloads](https://www.oracle.com/database/technologies/appdev/jdbc-ucp-19c-downloads.html)
@jjargot please note that ojdbc8-19.3.0.0.jar is now provided in the migration tool.
Can you update this PR accordingly?

2021-02-04 09:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=1151) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=1151) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: mariellebonita<br/>:white_check_mark: educhastenier<br/>:x: jjargot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-doc?pullRequest=1151) it.</sub>

2021-03-08 10:04 UTC, educhastenier commented on md/migrate-from-an-earlier-version-of-bonita-bpm.md
> +**Note I**: The migration tool already include the oracle driver for Oracle 19c (19.3.0.0) in the `bonita-migration/lib` directory. If your are not using Oracle 19c (19.3.0.0) you need to replace it.
```suggestion
**Note I**: The migration tool already includes the oracle driver for Oracle 19c (19.3.0.0) in the `bonita-migration/lib` directory. If your are not using Oracle 19c (19.3.0.0) you need to replace it.
```

2021-03-08 10:06 UTC, merged