fix(oracle): Add that we support Oracle 19c
bonitasoft/bonita-doc pull request #1155
Opened 2020-02-06 16:03 UTC by danila-m

* Modify installation guidance

2020-02-20 15:35 UTC, pabloalonso approved these changes

2020-02-21 08:45 UTC, jjargot requested changes
! Thank you for this update !

It is require to always mention the real full Oracle version used, such as Oracle 12c (12.2.0.x.y).
Once installed, connect to the server as Oracle user:
$ sqlplus / as sysdba
select * from v$version;

Q1- Would you mind to use the release version in the output of the SQL query above plus the marketing one all together?

The customers using the Oracle 12c (12.2.0.x.y) needs to run the initxa.sql and xaview.sql scripts, which are creating both the XA Subprograms and the XA views: AKA Oracle XA Library.

It is wise to implement 2 sections: 
 -1- Oracle 12c (12.2.0.x.y) -> current working procedure
 -2- Oracle 19c (? ? ? ? ? ?) -> new section

Q2- What do you think?


--
-- Oracle 19c (? ? ? ? ? ?) 

The official Oracle documentation pages regarding the Oracle XA Library have not changed.
That is why we think at support that the scripts are still needed.

I noticed that the XA Subprogram may be already installed with Enterprise Edition but on **Windows Only**

Q3- What do you think?

If both initxa.sql and xaview.sql scripts are delivered with the Oracle 19c installation, support suggests to let the customer run them: in other word, do not remove them from the procedure (plz)

Q4- What do you think?

If you agree with this, only one section will be needed for all Oracle versions, where the customers are instructed to tun the scripts.

--
-- A valuable check (AKA Feedback from customer site)

One customer did run several times the xa scripts to install the Oracle XA Library on the Oracle 12 (12.2.0.x.y) , but the changes were somehow rolled back. This was causing errors with bonita 7.9.

Christophe from PS has provided the procedure to test that the Oracle XA Libray is properly installed
'
Sur la base de données (Oracle) :

**Depuis le user bonita :**

Démarrer la transaction : call dbms_xa.xa_start(xid => dbms_xa_id(1234), flag => dbms_xa.tmnoflags) ;

vérifier la transaction (si ko, ce n’est pas correctement configuré) : dbms_xa.xa_ok et call dbms_xa.xa_getlastoer()

Suspendre la transaction : call dbms_xa.xa_end(xid => dbms_xa_id(1234), flag =>  dbms_xa.tmsuspend)

vérifier dbms_xa.xa_ok et call dbms_xa.xa_getlastoer() pour vérifier si tout va bien ou si il y a déjà une anomalie

vérifier qu’on retrouve la transaction : select state,  flags,  coupling from  gv$global_transaction where globalid = dbms_xa_xid(1234).gtrid;

**Depuis le user bdm :**

récupérer la transaction : call dbms_xa.xa_start(xid => dbms_xa_id(1234),   flag =>  dbms_xa.tmresume)

vérifier la transaction (si ko, ce n’est pas correctement configuré) : dbms_xa.xa_ok et call dbms_xa.xa_getlastoer()

Fermer la transaction : call dbms_xa.xa_end(xid => dbms_xa_id(1234), flag =>  dbms_xa.tmsuccess)

vérifier dbms_xa.xa_ok et call dbms_xa.xa_getlastoer() pour vérifier si tout va bien ou si il y a déjà une anomalie
'

It would be a great enhencement to include this check in the documentation.

Q5- What do you think?

2020-02-25 15:00 UTC, pabloalonso commented on md/database-configuration.md
> +The driver compatible with Oracle 12.2.0.x can be found here: [ojdbc8.jar](https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html) ( make sure it is the offical driver by checking t
Same driver for 12.2 and 19?

2020-02-25 15:00 UTC, pabloalonso commented on md/hardware-and-software-requirements.md
> +| Oracle                             | 12c (12.2.0.x), 19c (19.3.0.0.0) (see note 4)                      |
Why 19.3 and before 19.0?

2020-02-25 16:52 UTC, tbouffard commented on md/database-configuration.md
> +The driver compatible with Oracle 12.2.0.x can be found here: [ojdbc8.jar](https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html) ( make sure it is the offical driver by checking t
why not using the driver available on maven central?
https://medium.com/oracledevs/oracle-jdbc-drivers-on-maven-central-64fcf724d8b
can we embed it into bonita?

2020-02-26 08:51 UTC, pabloalonso commented on md/database-configuration.md
> +The driver compatible with Oracle 12.2.0.x can be found here: [ojdbc8.jar](https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html) ( make sure it is the offical driver by checking t
not for 7.9 and 7.10 as there are 2 different drivers. It can be in 7.11

2020-02-26 09:04 UTC, danila-m commented on md/database-configuration.md
> +The driver compatible with Oracle 12.2.0.x can be found here: [ojdbc8.jar](https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html) ( make sure it is the offical driver by checking t
We can, and probably will in 7.11. We did not in 7.10.

2020-02-26 09:07 UTC, merged

2020-02-27 02:08 UTC, mariellebonita commented on md/database-configuration.md
> +The driver compatible with Oracle 12.2.0.x can be found here: [ojdbc8.jar](https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html) ( make sure it is the offical driver by checking t
If you say that Oracle 19c (19.3.0.0) is supported, could you please provide the link to the driver for 19.3.0.0 and the checksum. It's a recurring source of giant problems, really it is a pita, and it must be over explained in the doc. Thanks for your understanding.

2020-02-27 08:49 UTC, danila-m commented on md/database-configuration.md
> +The driver compatible with Oracle 12.2.0.x can be found here: [ojdbc8.jar](https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html) ( make sure it is the offical driver by checking t
I did in this very PR ? 
If the resulting documentation https://documentation.bonitasoft.com/bonita/7.10/database-configuration is not clear somewhat please let me know.

2020-03-06 16:48 UTC, mariellebonita commented on md/database-configuration.md
> +The driver compatible with Oracle 12.2.0.x can be found here: [ojdbc8.jar](https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html) ( make sure it is the offical driver by checking t
Was the driver 967c0b1a2d5b1435324de34a9b8018d294f8f47b fully tested with both 12.2 and 12.3? Again, we've been down that road before, we know that each version of oracle needs the related specific driver version. so if there is one driver for 12.2 and one driver for 12.3, and an other one for both version, all cases should tested and documented in my opinion.