feat(dev-doc): add doc on BPMN events execution
bonitasoft/bonita-doc pull request #1294
Opened 2020-10-13 06:37 UTC by baptistemesta

2020-10-13 14:41 UTC, danila-m requested changes
I know you simply copy pasted what we had in the wiki, but IMO it should not be merged like that.

- I'm really not sure we want the remarks in the official documentation.

- At least the empty sections should be removed (or ideally filled)

2020-10-13 14:48 UTC, baptistemesta commented on md/how-an-event-is-executed.md
> +### Throw events
```suggestion
## Message Trigger
### Catch events
### Throw events
## Signal Trigger
### Catch events
### Throw events
## Timer Trigger
### Catch events
### Throw events
```

2020-10-13 14:48 UTC, baptistemesta commented on md/how-an-event-is-executed.md
> +* Creating fake values to call handlePostThrowEvent() in case of an error event on a connector does not look clean code...
```suggestion
```

2020-10-13 14:50 UTC, baptistemesta commented
> I know you simply copy pasted what we had in the wiki, but IMO it should not be merged like that.
> 
> * I'm really not sure we want the remarks in the official documentation.
> * At least the empty sections should be removed (or ideally filled)

I agree, I updated the PR

2020-10-14 07:42 UTC, danila-m approved these changes

2020-10-14 07:42 UTC, merged