Markdown + whitespace fixes
bonitasoft/bonita-doc pull request #145
Opened 2016-09-27 01:10 UTC by adam-nielsen

The current page doesn't terminate the XML formatting properly, so some of the Markdown code following the XML is formatted as if it's part of the XML code block.  This whitespace change fixes that.

2016-09-27 07:21 UTC, tnguyen1 commented
ok to test

2016-09-27 09:37 UTC, redboul requested changes

2016-09-27 09:37 UTC, redboul commented on md/web-service-tutorial.md
> -    ```
Actually, the opening \`\`\` should be aligned with the ending one. 
Ideally, we would like to indent it the previous line (aligned with `Envelope`)

2016-09-27 09:37 UTC, redboul commented on md/web-service-tutorial.md
> +```groovy
same here, aligned with `The`

2016-09-27 09:37 UTC, redboul commented on md/web-service-tutorial.md
>  ```
same here aligned with opening \`\`\`

2016-09-27 09:37 UTC, redboul commented on md/web-service-tutorial.md
>  ```
same here, this whole block should be aligned with the `Use`

2016-09-27 09:38 UTC, redboul commented
Hi Adam,

Thanks for your feedback !
Would you mind indent the content the way I suggested it please ?

Best regards

2017-02-16 14:13 UTC, educhastenier commented
retest this please

2017-02-16 14:32 UTC, educhastenier commented
Formatting ok like that.
Thanks for your contribution.

2017-02-16 14:33 UTC, merged

2017-02-20 02:51 UTC, adam-nielsen commented
Thanks all.  @redboul Sorry I didn't get a chance to update the formatting, I got moved into a different project.

2017-02-20 09:17 UTC, educhastenier commented
Your change is already online on version 7.3 and later here:
http://documentation.bonitasoft.com/7.3?page=web-service-tutorial :smile:
Thx