fix(rn): Provide a way to clean duplicated foreign keys
bonitasoft/bonita-doc pull request #1517
Opened 2021-04-01 13:04 UTC by danila-m

Provide a way to clean duplicated foreign keys caused by
RUNTIME-154/HHH-13779

Relates to [RUNTIME-154](https://bonitasoft.atlassian.net/browse/RUNTIME-154)

2021-04-02 14:30 UTC, pabloalonso requested changes

2021-04-02 14:30 UTC, pabloalonso commented on modules/ROOT/pages/release-notes.adoc
> +On Oracle, it is forbidden to generate such duplicated foreign keys, so the BDM redeployment operation fails. This is fixed in the next Bonita 2021.1 release.
This is in the 2021.1 RN so we should explain that this is fixed in the 2021.1-0408 "patch" version
```suggestion
On Oracle, it is forbidden to generate such duplicated foreign keys, so the BDM redeployment operation fails. This is fixed in the latest Bonita 2021.1 release (2021.1-0408)
```

2021-04-02 14:30 UTC, pabloalonso commented on modules/ROOT/pages/release-notes.adoc
> +1. Open the db in an edition tool (or execute in command line the relevant commands)
We should explain how to find the duplicated FKs and how to remove them.
What about a community question?

2021-04-07 11:11 UTC, pabloalonso commented on modules/ROOT/pages/release-notes.adoc
> +1. Open the db in an edition tool (or execute in command line the relevant commands)
move step by step with SQL commands into migrate-from-an-earlier-version-of-bonita-bpm

2021-06-15 14:02 UTC, alachambre commented
No activity for 2 months on this pull request, could you guys finihs it or drop it? @danila-m @pabloalonso

2021-07-06 13:44 UTC, educhastenier commented
This PR is duplicate of https://github.com/bonitasoft/bonita-doc/pull/1512.
=> Closing

2021-07-06 13:44 UTC, closed without merging