chore(rn): add release note of 2021.1-0617
bonitasoft/bonita-doc pull request #1597
Opened 2021-06-17 06:30 UTC by baptistemesta

2021-06-17 06:48 UTC, rbioteau commented on modules/ROOT/pages/release-notes.adoc
> +* STUDIO-3965 - Regression: Organization is reset to Acme or None after restart
```suggestion
* STUDIO-3965 - Active organization preference is not stored
```

2021-06-17 06:49 UTC, rbioteau commented on modules/ROOT/pages/release-notes.adoc
> +* STUDIO-3953 - LA Builder is slow
```suggestion
* STUDIO-3953 - Improve LA-Builder build performence
```

2021-06-17 06:50 UTC, rbioteau commented on modules/ROOT/pages/release-notes.adoc
> +* STUDIO-3948 - Git clone should not display migration warning message
```suggestion
* STUDIO-3948 - Git clone should not display migration warning message when not causing breaking changes
```

2021-06-17 07:31 UTC, NathalieC requested changes

2021-06-17 07:31 UTC, NathalieC commented on modules/ROOT/pages/release-notes.adoc
> +* UID-440 - dataTable don't sort date related columns when source is "Variable"
```suggestion
* UID-440 - dataTable does not sort date-related columns when source is "Variable"
```

2021-06-17 07:31 UTC, NathalieC commented on modules/ROOT/pages/release-notes.adoc
> +* UID-362 - Import custom widgets doesn't import assets
```suggestion
* UID-362 - Import custom widgets does not import assets
```

2021-06-17 07:31 UTC, NathalieC commented on modules/ROOT/pages/release-notes.adoc
> +
==== Fixes in Bonita Development Suite (Studio and UI Designer)

2021-06-17 07:31 UTC, NathalieC commented on modules/ROOT/pages/release-notes.adoc
> +* STUDIO-3948 - Git clone should not display migration warning message when not causing breaking changes
==== Fixes in Bonita Runtime (including Portal)

2021-06-17 07:31 UTC, NathalieC commented on modules/ROOT/pages/release-notes.adoc
> +Refresh results
?

2021-06-18 07:00 UTC, baptistemesta commented on modules/ROOT/pages/release-notes.adoc
> +Refresh results
```suggestion
```

2021-06-18 10:18 UTC, NathalieC approved these changes

2021-06-18 10:19 UTC, merged