tr(contributing): improve guidelines
bonitasoft/bonita-doc pull request #163
Opened 2016-10-06 09:27 UTC by redboul

* add PR naming convention
* clarify process of automatic TOC changes
* detail bootstrap alerts use cases

2016-10-10 13:25 UTC, tnguyen1 requested changes
Reviewed some wordings, typos and other links.

2016-10-10 13:25 UTC, tnguyen1 commented on CONTRIBUTING.md
> +A branch should be name in kebab case prefixes by the type of the feature the branch has bcreated for (fix, chore, howto,...).
- A branch should be *named in kebab-case and prefixed* by the type... has *been created for*...
- What does "chore" refer to ?
- Can we add a list like (feat, fix, style, howto, tr, ...) ?

2016-10-10 13:25 UTC, tnguyen1 commented on CONTRIBUTING.md
> +Having a single commit allows github to use the commit title as pull request name.
*GitHub*

2016-10-10 13:25 UTC, tnguyen1 commented on CONTRIBUTING.md
> +Checkout [the markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#blockquotes) for more information.
Can we link to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers or https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet instead?

2016-10-10 13:25 UTC, tnguyen1 commented on CONTRIBUTING.md
> +  - the Howtos are a step by step guide to manage a use case. This use case should be described briefly as an introduction (following the page title but without its own title) for the user to underst
Remove "the" ie "Howtos are a step ..."

2016-10-10 13:25 UTC, tnguyen1 commented on CONTRIBUTING.md
> +Current conversion to html is done with `markdown-it` with the [Github-flavored Markdown](https://help.github.com/categories/writing-on-github/). Checkout [the cheatsheet](https://github.com/adam-p/m
Use this link instead ? https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

2016-10-10 13:25 UTC, tnguyen1 commented on CONTRIBUTING.md
> +* danger : used to highlight error prone use cases
No space before colon I guess - https://en.wikipedia.org/wiki/Colon_(punctuation)#Spacing

2016-10-11 08:31 UTC, redboul commented on CONTRIBUTING.md
> +A branch should be name in kebab case prefixes by the type of the feature the branch has bcreated for (fix, chore, howto,...).
chore is maintenance job. 
In fact, I updated the list we have in other repos because all terms may be confusing, IMHO. 
I will add them all then.

2016-10-11 09:06 UTC, redboul commented on CONTRIBUTING.md
> +Current conversion to html is done with `markdown-it` with the [Github-flavored Markdown](https://help.github.com/categories/writing-on-github/). Checkout [the cheatsheet](https://github.com/adam-p/m
done

2016-10-11 09:06 UTC, redboul commented on CONTRIBUTING.md
> +* danger : used to highlight error prone use cases
done

2016-10-11 09:06 UTC, redboul commented on CONTRIBUTING.md
> +  - the Howtos are a step by step guide to manage a use case. This use case should be described briefly as an introduction (following the page title but without its own title) for the user to underst
done

2016-10-11 09:06 UTC, redboul commented on CONTRIBUTING.md
> +Checkout [the markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#blockquotes) for more information.
done

2016-10-11 09:06 UTC, redboul commented on CONTRIBUTING.md
> +Having a single commit allows github to use the commit title as pull request name.
done

2016-10-11 10:00 UTC, tnguyen1 commented on CONTRIBUTING.md
> +A branch should be name in kebab case prefixes by the type of the feature the branch has bcreated for (fix, chore, howto,...).
Sentence typos has not been integrated yet.

2016-10-11 14:46 UTC, redboul commented on CONTRIBUTING.md
> +A branch should be name in kebab case prefixes by the type of the feature the branch has bcreated for (fix, chore, howto,...).
oups

2016-10-17 16:08 UTC, tnguyen1 approved these changes

2016-10-17 16:09 UTC, merged