feat(doc): ldap tenant id and docker image
bonitasoft/bonita-doc pull request #1659
Opened 2021-08-16 12:42 UTC by baptistemesta

add it to the release note and add the new property `tenantId` and `BONITA_TENANT_ID` to the documenation

Relates to [RUNTIME-425](https://bonitasoft.atlassian.net/browse/RUNTIME-425)
Closes [RUNTIME-435](https://bonitasoft.atlassian.net/browse/RUNTIME-435)

2021-08-16 13:16 UTC, educhastenier commented on modules/ROOT/pages/ldap-synchronizer.adoc
> -Learn how to configure the LDAP Synchronizer. This tool updates Bonita Users and Groups database from the LDAP directory.
revert this

2021-08-16 13:16 UTC, educhastenier commented on modules/ROOT/pages/ldap-synchronizer.adoc
> -to match as closely as possible the user list attributes defined in LDAP. It does not modify the LDAP directory.
revert this

2021-08-16 13:16 UTC, educhastenier commented on modules/ROOT/pages/ldap-synchronizer.adoc
> -The synchronizer program runs in the background. There is no user interface: all configuration settings are specified in files and
revert this

2021-08-16 13:17 UTC, educhastenier commented on modules/ROOT/pages/ldap-synchronizer.adoc
revert this

2021-08-16 13:18 UTC, educhastenier commented on modules/ROOT/pages/ldap-synchronizer.adoc
> -NOTE: to use a special character in a properties file, use the Unicode equivalent. For example, for `à` use \u00E0.
revert this

2021-08-16 13:18 UTC, educhastenier commented on modules/ROOT/pages/ldap-synchronizer.adoc
> -* logger.properties provides the settings for the logger. Default settings should be fine for most uses.
revert this

2021-08-16 13:18 UTC, educhastenier requested changes
Revert some space removals

2021-08-16 13:48 UTC, rbioteau commented on modules/ROOT/pages/ldap-synchronizer.adoc
> +Learn how to configure the LDAP Synchronizer.This tool updates Bonita Users and Groups database from the LDAP directory.
```suggestion
Learn how to configure the LDAP Synchronizer. This tool updates Bonita Users and Groups database from the LDAP directory.
```

2021-08-16 13:48 UTC, rbioteau commented on modules/ROOT/pages/ldap-synchronizer.adoc
> +to match as closely as possible the user list attributes defined in LDAP.It does not modify the LDAP directory.
```suggestion
to match as closely as possible the user list attributes defined in LDAP. It does not modify the LDAP directory.
```

2021-08-16 13:48 UTC, rbioteau commented on modules/ROOT/pages/ldap-synchronizer.adoc
> +The synchronizer program runs in the background.There is no user interface: all configuration settings are specified in files and
```suggestion
The synchronizer program runs in the background. There is no user interface: all configuration settings are specified in files and
```

2021-08-17 08:52 UTC, baptistemesta commented on modules/ROOT/pages/ldap-synchronizer.adoc
> +* logger.properties provides the settings for the logger.Default settings should be fine for most uses.
```suggestion
* logger.properties provides the settings for the logger. Default settings should be fine for most uses.
```

2021-08-17 08:53 UTC, baptistemesta commented on modules/ROOT/pages/ldap-synchronizer.adoc
> +NOTE: to use a special character in a properties file, use the Unicode equivalent.For example, for `à` use \u00E0.
```suggestion
NOTE: to use a special character in a properties file, use the Unicode equivalent. For example, for `à` use \u00E0.
```

2021-08-17 08:53 UTC, baptistemesta commented on modules/ROOT/pages/ldap-synchronizer.adoc
> +NOTE: Some use cases require additional configuration server side (for example to use directly the engine API).They are described xref:configure-client-of-bonita-bpm-engine.adoc[here].
```suggestion
NOTE: Some use cases require additional configuration server side (for example to use directly the engine API). They are described xref:configure-client-of-bonita-bpm-engine.adoc[here].
```

2021-08-17 08:57 UTC, merged