fix(performance-troubleshooting): improve connectors
bonitasoft/bonita-doc pull request #1681
Opened 2021-08-26 23:16 UTC by mariellebonita

* fix links in Connectors section
* Add more details

2021-08-27 14:53 UTC, educhastenier commented on modules/ROOT/pages/performance-troubleshooting.adoc
> +For Subscription Edition only, this timeout can be increased in the Connector service configuration in `bonita-tenant-community-custom.properties` and `bonita-tenant-sp-custom.properties` (See xref:B
```suggestion
[NOTE]
====
for subscription editions only.
====
This timeout can be increased in the Connector service configuration in  `bonita-tenant-sp-custom.properties` (See xref:BonitaBPM_platform_setup.adoc[platform setup]) by increasing the value of the property `bonita.tenant.connector.timeout`.  
```

2021-08-27 14:59 UTC, educhastenier requested changes
Remove erroneous reference to configuration file bonita-tenant-community-custom.properties

2021-08-30 17:55 UTC, mariellebonita commented
Thanks @educhastenier , LGTM, feel free to merge 👍

2021-10-04 10:52 UTC, tbouffard commented on modules/ROOT/pages/performance-troubleshooting.adoc
> +for subscription editions only.
⚠️ This is not the wording we use in other page.

![image](https://user-images.githubusercontent.com/27200110/135838915-9616aa0f-3554-44c9-aa04-c779e8cc531f.png)

or "In Teamwork, Efficiency, Performance and Enterprise editions"

2021-10-04 13:12 UTC, educhastenier approved these changes

2021-10-04 13:13 UTC, merged