feat(docker): Explain how to configure a postgres container for bonita
bonitasoft/bonita-doc pull request #1748
Opened 2021-10-01 08:52 UTC by danila-m

Relates to [RUNTIME-544](https://bonitasoft.atlassian.net/browse/RUNTIME-544)

2021-10-01 13:48 UTC, educhastenier commented on modules/ROOT/pages/bonita-docker-installation.adoc
> +The configuration of a PostgreSQL database to work with Bonita is described in detail in the xref:database-configuration.adoc[database configuration page]
```suggestion
The configuration of a PostgreSQL database to work with Bonita is described in detail in the xref:database-configuration.adoc[database configuration page]. +
```

2021-10-01 13:52 UTC, educhastenier commented on modules/ROOT/pages/bonita-docker-installation.adoc
> +Alternatively, Bonita provides a preconfigured https://hub.docker.com/repository/docker/bonitasoft/bonita-postgres[postgres image] on docker-hub
```suggestion
Alternatively, Bonita provides a preconfigured https://hub.docker.com/r/bonitasoft/bonita-postgres[PostgreSQL image] on docker-hub. +
```

2021-10-01 13:52 UTC, educhastenier commented on modules/ROOT/pages/bonita-docker-installation.adoc
> +You can run the image with the following command
```suggestion
You can run the image with the following command:
```

2021-10-01 13:53 UTC, educhastenier commented on modules/ROOT/pages/bonita-docker-installation.adoc
> +docker run --name mydbpostgres -h <hostname> -v bonita-lic:/opt/bonita_lic/ -d bonitasoft/bonita-postgres:12.6
```suggestion
docker run --name mydbpostgres -h <hostname> -v <your-bonita-license-folder>:/opt/bonita_lic/ -d bonitasoft/bonita-postgres:12.6
```

2021-10-01 13:55 UTC, educhastenier requested changes
Also modify docker-compose yaml example from
image: postgres:11.2
to
image: postgres:12.6

2021-10-04 07:43 UTC, baptistemesta commented
there are reference to ENSURE_DB_CHECK_AND_CREATION here: https://documentation.bonitasoft.com/bonita/2021.2/bonita-docker-installation#_ensure_db_check_and_creation

2021-10-04 08:17 UTC, educhastenier approved these changes

2021-10-04 08:20 UTC, merged