doc(API calls): Reference all accessible APIs for a default installation
bonitasoft/bonita-doc pull request #1756
Opened 2021-10-06 15:33 UTC by DumitruCorini

covers [RUNTIME-526](https://bonitasoft.atlassian.net/browse/RUNTIME-526)

- [x] User Application
- [x] Administrator Application
- [x] Application Directory
- [x] Super Administrator Application

2021-10-08 13:19 UTC, DumitruCorini commented
Ready to review

2021-10-13 14:10 UTC, alachambre requested changes
- Do not add links in asciidoc variables, move theme outside the description for SEO. 
- Please do not talk about the Super Administrator as a Profile, it is NOT a profile, it could lead to confusion for users. 
- Please use the preview to validate your content when you contribute ot the documentation, it would save a lot of time to your reviewers...

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-admin.adoc
> +:description: This page explains the REST API permissions for the Administrator profile. More information about how this page is structured can be found xref:default-api-permissions-overview.adoc[in
```suggestion
:description: This page explains the REST API permissions for the Administrator profile.
```

You should not add a link in an asciidoc variable, it is not correctly parsed at build time. You would have noticed if you opened the preview.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-admin.adoc
> +{description} +
```suggestion
{description}. More information about how this page is structured can be found xref:default-api-call-permissions-overview.adoc[in this page]. +
```

Move the link outside the description variable. And the link himself was wrong.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-all.adoc
> +:description: This page explains the REST API permissions for All profiles. More information about how this page is structured can be found xref:default-api-permissions-overview.adoc[in this page].
```suggestion
:description: This page explains the REST API permissions for All profiles.
```

You should not add a link in an asciidoc variable, it is not correctly parsed at build time. You would have noticed if you opened the preview.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-all.adoc
> +{description} +
```suggestion
{description}. More information about how this page is structured can be found xref:default-api-call-permissions-overview.adoc[in this page]. +
```

Move the link outside the description variable. And the link himself was wrong.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-overview.adoc
> +You can view the following pages for each profile :
Super Administrator is not a profile, this is a concept you introduced with your new applications but this is NOT a Bonita profile, you cannot write this. 
I suggest you to talk about the super administrator user. 
Furthermore, the Process manager profile is missing in your list.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-overview.adoc
> +You can view the following pages for each profile :
```suggestion
You can view the following pages for each profile :

```
You must add a line break to use a bullet list after. You would have noticed if you opened the preview of your pull request...

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-super-admin.adoc
> +:description: This page explains the REST API permissions for the Super Administrator profile. More information about how this page is structured can be found xref:default-api-permissions-overview.ad
```suggestion
:description: This page explains the REST API permissions for the Super Administrator profile.
```

You should not add a link in an asciidoc variable, it is not correctly parsed at build time. You would have noticed if you opened the preview.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-super-admin.adoc
> +{description} +
```suggestion
{description}. More information about how this page is structured can be found xref:default-api-call-permissions-overview.adoc[in this page]. +
```
Move the link outside the description variable. And the link himself was wrong.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-super-admin.adoc
> +== Subscription Editions
```suggestion

== Subscription Editions
```

You must add a line break before a new section. You would have noticed if you opened the preview.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-user.adoc
> +:description: This page explains the REST API permissions for the User profile. More information about how this page is structured can be found xref:default-api-permissions-overview.adoc[in this page
```suggestion
:description: This page explains the REST API permissions for the User profile.
```

You should not add a link in an asciidoc variable, it is not correctly parsed at build time. You would have noticed if you opened the preview.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-user.adoc
> +{description} +
```suggestion
{description}. More information about how this page is structured can be found xref:default-api-call-permissions-overview.adoc[in this page]. +
```

Move the link outside the description variable. And the link himself was wrong.

2021-10-13 14:10 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-super-admin.adoc
> +This profile is linked to the Bonita Super Administrator Application by default. More information about this application can be found in the xref:super-administrator-application-overview.adoc[Super A
Again, the 'Super Administrator' is NOT a Bonita profile, you cannot say that. I suggest you to talk about the super administrator user.

2021-10-15 12:35 UTC, alachambre commented
Let me know when you'll work again on this pull request, you'll have to re-create it to take into account the modules, i'll help you.
I do not want to do it for you and close this one because you would miss my comments.

2021-10-20 08:35 UTC, abirembaut requested changes
just 2 more small comments in addition of the ones of Adrien

2021-10-20 08:35 UTC, abirembaut commented on modules/ROOT/pages/rest-api-authorization.adoc
> +You can find the rest API authorizations xref:default-api-call-permissions-overview.adoc[in this page].
```suggestion
You can find the rest API authorizations in xref:default-api-call-permissions-overview.adoc[this page].
```

2021-10-20 08:35 UTC, abirembaut commented on modules/ROOT/taxonomy.adoc
> +   **** xref:default-api-call-permissions-super-admin.adoc[Super Administrator profile permissions]
```suggestion
   **** xref:default-api-call-permissions-super-admin.adoc[Super Administrator permissions]
```

2021-10-26 09:38 UTC, DumitruCorini commented on modules/ROOT/pages/default-api-call-permissions-overview.adoc
> +You can view the following pages for each profile :
The process manager has no more permissions by default

2021-10-26 09:39 UTC, DumitruCorini commented on modules/ROOT/pages/default-api-call-permissions-overview.adoc
> +You can view the following pages for each profile :
For the supervisor, it acts like a pseudo-profile in the new version. "All profiles" and "Super administrator" don't appear in the list of profiles, but these two are connected in the same way that profiles are connected to their apps (through the notion of profiles).

2021-10-26 09:43 UTC, DumitruCorini commented on modules/ROOT/pages/default-api-call-permissions-overview.adoc
> +You can view the following pages for each profile :
@pabloalonso , need your input on this, I guess...

2021-10-26 09:44 UTC, DumitruCorini commented on modules/ROOT/pages/default-api-call-permissions-super-admin.adoc
> +This profile is linked to the Bonita Super Administrator Application by default. More information about this application can be found in the xref:super-administrator-application-overview.adoc[Super A
See above comment

2021-10-26 11:55 UTC, alachambre commented on modules/ROOT/pages/default-api-call-permissions-overview.adoc
> +You can view the following pages for each profile :
Yes, but you cannot use the super admin as a profile for anything else, so do not reference it as a profile, it'll lead to confusion. Or make it a profile.

2021-10-26 12:02 UTC, alachambre requested changes

2021-10-26 12:02 UTC, alachambre commented on modules/identity/pages/rest-api-authorization.adoc
> +You can find the rest API authorizations xref:default-api-call-permissions-overview.adoc[in this page].
As explained a few weeks ago, we added Modules on the documentation since 2021.2

It means that to reference a page in an other module you must reference the targeted module in the link -> `xref:module:page`

In your use case, I suggest you to to move the permissions pages in the identity module, it is the purpose of this module. An by doing that you'll be able to reference the pages wihtout adding the module. 

Again, let me know if you need some help to understand this.

2021-10-26 12:03 UTC, alachambre commented
You didn't add your pages in any navigation page, is it on purpose?

2021-10-26 12:05 UTC, alachambre commented
Please rename your permission pages, the p[age name is reflected in the URL, `default-api-call-permissions-admin.adoc` is not relevant in an URL. I suggest something like admin-permissions, so the URL will be readable. 
Thanks

2021-10-26 12:08 UTC, DumitruCorini commented on modules/ROOT/pages/default-api-call-permissions-overview.adoc
> +You can view the following pages for each profile :
We'll talk about it tomorrow in daily

2021-10-26 12:20 UTC, DumitruCorini commented on modules/ROOT/pages/rest-api-authorization.adoc
> +You can find the rest API authorizations xref:default-api-call-permissions-overview.adoc[in this page].
Done

2021-10-26 12:23 UTC, DumitruCorini commented on modules/ROOT/taxonomy.adoc
> +   **** xref:default-api-call-permissions-super-admin.adoc[Super Administrator profile permissions]
Added

2021-10-26 12:23 UTC, DumitruCorini commented on modules/identity/pages/rest-api-authorization.adoc
> +You can find the rest API authorizations xref:default-api-call-permissions-overview.adoc[in this page].
Ok, I did this

2021-10-26 12:24 UTC, DumitruCorini commented on modules/identity/pages/rest-api-authorization.adoc
> +You can find the rest API authorizations xref:default-api-call-permissions-overview.adoc[in this page].
Added

2021-10-26 12:26 UTC, DumitruCorini commented
Probably a miss on my side for the taxonomy (even if I thought I did add it).
I'll change all the urls I guess.

2021-10-26 12:46 UTC, DumitruCorini commented on modules/ROOT/pages/default-api-call-permissions-overview.adoc
> +You can view the following pages for each profile :
After a second thought, I rewrote the part of the super admin user.

2021-10-26 12:46 UTC, DumitruCorini commented on modules/ROOT/pages/default-api-call-permissions-super-admin.adoc
> +This profile is linked to the Bonita Super Administrator Application by default. More information about this application can be found in the xref:super-administrator-application-overview.adoc[Super A
This was re-written

2021-11-16 08:44 UTC, abirembaut approved these changes

2021-11-16 08:44 UTC, abirembaut commented
LGTM

2021-11-16 08:45 UTC, merged