update(runtime nav): add admin index
bonitasoft/bonita-doc pull request #1800
Opened 2021-10-25 08:30 UTC by NathalieC

* add a reference to the administration index page.

2021-10-26 12:23 UTC, alachambre requested changes

2021-10-26 12:23 UTC, alachambre commented on modules/runtime/pages/administration-index.adoc
> +
Useless linebreak
```suggestion
```

2021-10-26 12:23 UTC, alachambre commented on modules/runtime/runtime-nav.adoc
> + ** xref:runtime-administration.adoc[Administration]
Your index page is named `administration-index.adoc`... 
I beg you to use the preview to detect those issues before review 🙏 

```suggestion
 ** xref:administration-index.adoc[Administration]
```

2021-10-26 12:23 UTC, alachambre commented on modules/runtime/pages/administration-index.adoc
> +xref:ROOT:back-up-bonita-bpm-platform.adoc[[.card-title]#Runtime backups# [.card-body.card-content-overflow]#pass:q[The backup creation procedure to perform before a maintenance operation]#]
Too long for the content of the card. 
Preview :)

2021-10-26 12:32 UTC, NathalieC commented
You are too fast for me! It was not ready for review. I usually add the "review needed" label when it is.
But I forgot to put it in WIP / draft, so anyway, thank you for your review.
I'm applying the changes.

2021-10-26 12:46 UTC, alachambre commented
> You are too fast for me! It was not ready for review. I usually add the "review needed" label when it is. But I forgot to put it in WIP / draft, so anyway, thank you for your review. I'm applying the changes.

Haha sorry 😅

2021-10-26 13:31 UTC, NathalieC commented on modules/runtime/pages/administration-index.adoc
> +xref:ROOT:back-up-bonita-bpm-platform.adoc[[.card-title]#Runtime backups# [.card-body.card-content-overflow]#pass:q[The backup creation procedure to perform before a maintenance operation]#]
fixed

2021-10-26 13:33 UTC, NathalieC commented on modules/runtime/pages/administration-index.adoc
> +xref:ROOT:back-up-bonita-bpm-platform.adoc[[.card-title]#Runtime backups# [.card-body.card-content-overflow]#pass:q[The backup creation procedure to perform before a maintenance operation]#]
fixed

2021-10-27 09:44 UTC, alachambre reviewed
Just a few suggestions, it's up to you to integrate them or not, then you can merge 👍

2021-10-27 09:44 UTC, alachambre commented on modules/runtime/pages/administration-index.adoc
> +:description: This page gives an easy access to the administration features in Bonita Runtime.
```suggestion
:description: This page gives an easy access to the documentation of the administration features in Bonita Runtime.
```

2021-10-27 09:44 UTC, alachambre commented on modules/runtime/pages/administration-index.adoc
> +xref:ROOT:live-update.adoc[[.card-title]#Live Update# [.card-body.card-content-overflow]#pass:q[Very handy emergency actions you can take on a Runtime]#]
Since Live Update should indeed only be used for emergency actions, I suggest to avoid to call it 'very handy', it could give this impression that it is something nice to use.
And it is not 'very handy', it can gives this impression but it only leads to a production environment in an unknown state.
This feature should be removed 😛 

```suggestion
xref:ROOT:live-update.adoc[[.card-title]#Live Update# [.card-body.card-content-overflow]#pass:q[Emergency actions you can take on a Runtime]#]
```

2021-10-27 09:48 UTC, alachambre approved these changes

2021-10-28 08:19 UTC, NathalieC commented on modules/runtime/pages/administration-index.adoc
> +xref:ROOT:live-update.adoc[[.card-title]#Live Update# [.card-body.card-content-overflow]#pass:q[Very handy emergency actions you can take on a Runtime]#]
good feedback. You are right (except for the removal part :]). Thanks.

2021-10-28 08:21 UTC, merged