feat(tests): Init test toolkit documentation
bonitasoft/bonita-doc pull request #1809
Opened 2021-10-29 15:00 UTC by alachambre

2021-10-29 16:17 UTC, rbioteau requested changes

2021-10-29 16:17 UTC, rbioteau commented on modules/process/pages/process-integration-test.adoc
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0
some dependencies are not required and some plugins are not configured

2021-11-02 11:05 UTC, alachambre commented on modules/process/pages/process-integration-test.adoc
> +    public void should_create_a_tyrannosaurus(BonitaTestToolkit toolkit) throws Exception { <2>
```suggestion
    public void should_create_an_hungry_tyrannosaurus(BonitaTestToolkit toolkit) throws Exception { <2>
```

2021-11-02 14:03 UTC, educhastenier commented on modules/process/pages/process-integration-test.adoc
> +However, it based on the open source https://github.com/bonitasoft/bonita-java-client[Bonita Java Client] to make HTTP calls on the Bonita platform. Any user can make its own test toolkit using this
```suggestion
However, it is based on the open source https://github.com/bonitasoft/bonita-java-client[Bonita Java Client] to make HTTP calls to the Bonita runtime. Any user can make their own test toolkit using this client. 
```

2021-11-02 14:04 UTC, educhastenier commented on modules/process/pages/process-integration-test.adoc
> +In the world of development, writing tests is not an option. It is the best way to ensure that a product fulfill its requirements, and that existing existing features won't be broken by future develo
```suggestion
In the world of development, writing tests is not an option. It is the best way to ensure that a product fulfill its requirements, and that existing features won't be broken by future developments. 
```

2021-11-02 14:05 UTC, educhastenier commented on modules/process/pages/process-integration-test.adoc
> +This apply to Bonita processes. For each process, an integration test should be written, to validate that the process executes correctly depending on the inputs, that after each task the platform is
```suggestion
This applies to Bonita processes. For each process, an integration test should be written, to validate that the process executes correctly depending on the inputs, that after each task the platform is in the expected state and so on.
```

2021-11-02 14:07 UTC, benjaminParisel commented on modules/process/pages/process-integration-test.adoc
> +        BonitaAssertions.assertThat(processInstance).containsPendingTasks("CreateDinosaur"); <7>
```suggestion
        BonitaAssertions.assertThat(processInstance).containsPendingUserTasks("CreateDinosaur"); <7>
```

2021-11-03 08:49 UTC, alachambre commented on modules/process/pages/process-integration-test.adoc
> +            <groupId>org.apache.maven.plugins</groupId>
```suggestion
<plugin>
            <groupId>org.apache.maven.plugins</groupId>
```

2021-11-03 08:49 UTC, alachambre commented on modules/process/pages/process-integration-test.adoc
> +        </plugins>
```suggestion
</plugin>
        </plugins>
```

2021-11-16 09:42 UTC, merged