Update multi-tenancy-and-tenant-configuration.adoc
bonitasoft/bonita-doc pull request #1846
Opened 2021-11-26 08:31 UTC by vbotnari12

Based on the discussion during Top Customer meeting, the doc on multi-tenancy version 2021.2 is to be backported on 2021.1.

2021-11-26 08:41 UTC, alachambre reviewed
A few suggestions, else it looks fine 👍

2021-11-26 08:41 UTC, alachambre commented on modules/ROOT/pages/multi-tenancy-and-tenant-configuration.adoc
> +This feature was deprecated in Bonita 2021.1. This means that Multi-tenant architecture will continue to work in Bonita for existing Bonita subscription customers,
I think there is no need to say 'in 2021.1', you are already on the 2021.1 documentation. 
It is either you are on a deprecated version or not, so just say 'it is deprecated' when it is the case. 

```suggestion
This feature is deprecated. +
This means that Multi-tenant architecture will continue to work in Bonita for existing Bonita subscription customers,
```

2021-11-26 08:41 UTC, alachambre commented on modules/ROOT/pages/multi-tenancy-and-tenant-configuration.adoc
> +As mentioned in the release note, Bonita Enterprise customers need a contractual agreement to create additional tenants. For any new tenant creation, any general or contractual question related to Mu
```suggestion
As mentioned in the release note, Bonita Enterprise customers need a contractual agreement to create additional tenants. +
For any new tenant creation, any general or contractual question related to Multi-tenancy, please contact your customer success representative.
```

2021-11-29 13:21 UTC, tbouffard requested changes
⚠️ Please close this Pull Request
A Pull Request targeting the Bonita 7.10 documentation already exists (#1848). Once merged into 7.10, changes will be propagated to all subsequent Bonita versions (7.11 to 2022.1).

2021-12-21 14:49 UTC, pabloalonso commented
LGTM

2021-12-21 14:49 UTC, pabloalonso approved these changes

2021-12-21 14:50 UTC, merged