Update processes.md
bonitasoft/bonita-doc pull request #193
Opened 2016-11-10 13:40 UTC by HappyBonita

Return from Mariel&PYM

2016-11-10 14:25 UTC, educhastenier requested changes

2016-11-10 14:25 UTC, educhastenier commented on md/processes.md
> +Disable a process can block the creation of new cases, this does not impact existing cases and the use for call activities.
Disab**ling** ...

2016-11-10 14:25 UTC, educhastenier commented on md/processes.md
> +Disable a process can block the creation of new cases, this does not impact existing cases and the use for call activities.
From version 7.4.0 on, a disabled process cannot be started by a call-activity anymore. This was a bug fix.

2016-11-10 14:25 UTC, baptistemesta commented
Please follow the commit rules ( commit message and description )
https://bonitasoft.atlassian.net/wiki/display/BS/Contribute+to+Bonita+BPM
https://github.com/bonitasoft/bonita-developer-resources/blob/master/CONTRIBUTING.MD

2016-11-10 14:30 UTC, HappyBonita commented
i create a new commit

2017-01-19 16:44 UTC, educhastenier approved these changes

2017-01-19 16:45 UTC, merged