doc(RN): Update release note for release 2022.2
bonitasoft/bonita-doc pull request #1933
Opened 2022-02-09 10:53 UTC by Shmayro

2022-02-10 10:46 UTC, benjaminParisel commented
You need to update .github/workflow/push-content.yml too :) Ping me if you need more information.

2022-03-03 10:32 UTC, tbouffard commented
Can we merge this pull request?

2022-03-04 10:49 UTC, tbouffard requested changes
Please fix xref errors @Shmayro

2022-03-18 10:30 UTC, tbouffard approved these changes

2022-03-18 10:31 UTC, merged