Update pages.md
bonitasoft/bonita-doc pull request #194
Opened 2016-11-10 14:22 UTC by HappyBonita

Modif for 7.3.3

2016-11-10 15:08 UTC, educhastenier commented on md/pages.md
> +1. Import your custom page zip archive into the portal. This creates a directory `<TOMCAT_HOME>/temp/bonita_portal_*/tenants/tenant_id/pages/custompage_<your custom page>`.
I wouldn't put references to `<TOMCAT_HOME>` because this doc page is not only valid for Tomcat.
Moreover, `<java.io.tmpdir>` was correct:
- in Tomcat java.io.tmpdir=TOMCAT_HOME/temp
- in WildFly, java.io.tmpdir=DEFAULT_JVM_TMPDIR

So this doc is valid for both

2016-11-10 15:08 UTC, educhastenier commented on md/pages.md
> +3. You can now update `Index.groovy` and the contents of the `lib` directory directly in `<TOMCAT_HOME>/temp/bonita_portal_*/tenants/tenant_id/pages/custompage_<your custom page>`.
Same remark

2016-11-10 15:10 UTC, educhastenier commented
retest this please

2016-11-10 15:16 UTC, educhastenier commented on md/pages.md
> +::: Before use setup tool for the studio context, you need to edit the file : `database.properties`, and re-define ``h2.database.dir=../../<yourRepository>/h2_database`  :::
1. This is very weird to talk about setup-tool here
2. Be careful, this is not the right syntax for `:::`
3. you have extra **`**

2016-12-08 09:16 UTC, educhastenier commented
retest this please

2016-12-08 09:46 UTC, educhastenier requested changes

2016-12-08 09:46 UTC, educhastenier commented on md/pages.md
> +Before use setup tool for the studio context, you need to edit the file : `database.properties`, and re-define `h2.database.dir=../../<yourRepository>/h2_database`
1- This is still weird to talk about setup tool here. You must at least explain why this file change is needed.
And link to the setup tool doc page to make it clearer.

2- you say `Before use setup tool...` but then you don't talk about setup tool. Something is missing...

2016-12-08 09:48 UTC, educhastenier commented on md/pages.md
> +`<java.io.tmpdir>` for Tomcat platform is `<TOMCAT_HOME>/temp/`
The way we generally phrase our sentences in the documentation whould rather be like:

On a Tomcat installation, `<java.io.tmpdir>` points to `<TOMCAT_HOME>/temp/`

2017-02-16 14:02 UTC, educhastenier commented
Hello?
Can you answer by remarks?

2017-02-16 14:07 UTC, Happykiller commented on md/pages.md
> +`<java.io.tmpdir>` for Tomcat platform is `<TOMCAT_HOME>/temp/`
Oki thx

2017-03-02 15:39 UTC, educhastenier commented
Could you do something with this PR please?

2017-03-03 08:31 UTC, educhastenier commented
Thanks for your contribution.

2017-03-03 08:32 UTC, merged