Fix(troubleshooting sections 2nd batch): add icons and standardized sections
bonitasoft/bonita-doc pull request #1943
Opened 2022-02-22 15:46 UTC by NathalieC

* in Bonita Studio pref and config: add image for troubleshooting
* in Bonita Studio pref and config: add line breaks in troubleshooting section

2022-02-24 10:03 UTC, alachambre requested changes
I think the two sso troobleshooting sections should be moved at the bottom of the pages.

2022-02-24 10:03 UTC, alachambre commented on modules/identity/pages/single-sign-on-with-oidc.adoc
> -== Troubleshoot
Why is this section not at the bottom of the page, like in all other pages?

2022-02-24 10:03 UTC, alachambre commented on modules/identity/pages/single-sign-on-with-saml.adoc
> +== image:ROOT:images/troubleshooting.png[troubleshooting-icon] Troubleshooting
Why is this section not at the bottom of the page?

2022-03-07 13:53 UTC, NathalieC commented on modules/identity/pages/single-sign-on-with-oidc.adoc
> -== Troubleshoot
thanks. done.

2022-03-07 13:55 UTC, NathalieC commented on modules/identity/pages/single-sign-on-with-saml.adoc
> +== image:ROOT:images/troubleshooting.png[troubleshooting-icon] Troubleshooting
thx. done

2022-04-01 10:36 UTC, closed without merging