feat(http api): update doc with new easy way to (de)activate
bonitasoft/bonita-doc pull request #1977
Opened 2022-03-08 13:31 UTC by educhastenier

HTTP API from version 7.13.0

2022-03-15 13:56 UTC, vbotnari12 reviewed
Ok for me.

2022-03-28 13:47 UTC, baptistemesta requested changes
All good. IMHO, the only thing to change is the command line to run docker with HTTP that require a password

2022-03-28 13:47 UTC, baptistemesta commented on modules/identity/pages/ldap-synchronizer.adoc
> +* For example: `docker run -e HTTP_API=true -e REST_API_DYN_AUTH_CHECKS=false --name bonita -v ./bonita-lic/:/opt/bonita_lic/ -h localhost -d -p 8080:8080 quay.io/bonitasoft/bonita-subscription:pass:
That will fail because of the missing `HTTP_PASSWORD` (I'm not sure about the variable name)

2022-03-29 12:25 UTC, educhastenier commented on modules/identity/pages/ldap-synchronizer.adoc
> +* For example: `docker run -e HTTP_API=true -e REST_API_DYN_AUTH_CHECKS=false --name bonita -v ./bonita-lic/:/opt/bonita_lic/ -h localhost -d -p 8080:8080 quay.io/bonitasoft/bonita-subscription:pass:
@baptistemesta no, on 2021.2, this line is valid.
And in 2022.1, it has been updated already.

nothing wrong here 😉

2022-04-06 09:13 UTC, merged