docs(web): Fix errors in the Getting Started (2021.1)
bonitasoft/bonita-doc pull request #1998
Opened 2022-03-16 15:40 UTC by mbource

Fix errors in the Getting Started tutorial. 

Here's a report of what I changed in the PR :
- In https://documentation.bonitasoft.com/bonita/2021.1/draw-bpmn-diagram ->  Dead link: https://www.bonitasoft.com/library/ultimate-guide-bpmn , I change it with the one working. 

- In https://documentation.bonitasoft.com/bonita/2021.1/define-business-data-model ->  Step 9 : Finish button don’t exist in the UI. I do believe it’s supposed to say “Deploy” because first time I didnt deploy the BDM and I couldn’t use the application with the business data. It can be confusing. 

- In https://documentation.bonitasoft.com/bonita/2021.1/define-who-can-do-what , end of article, the sentence “Run the process again, and this time only mauro.zetticci should have access to Read the answer and rate it” is wrong. This is not the task Read the answer and rate it but Review and answer claim who should be mark on the doc.

2022-03-18 11:22 UTC, tbouffard commented
@mbource about the Dead link fix in `/draw-bpmn-diagram`
It has already been fixed in #1997 for version `7.11`. The change will be propagated automatically to newest versions thanks to this GitHub workflow: https://github.com/bonitasoft/bonita-documentation-site/blob/master/.github/workflows/propagate-doc-upwards.yml
So there is no need to redo the fix here and in #1996.

This is a general rule: we always do the changes in the oldest version to have them apply to all versions. In some cases, we have to do adaptations for newer versions, but otherwise, we only manage the changes once.
Please contact me if you need more information or clarifications 😸

2022-03-22 15:29 UTC, tbouffard requested changes
See https://github.com/bonitasoft/bonita-doc/pull/1998#issuecomment-1072318004

2022-03-23 08:02 UTC, mbource commented
Removing the dead link fix (already in 7.11 now) + adding all the suggestion of @NathalieC (https://github.com/bonitasoft/bonita-doc/pull/1996#issuecomment-1073639513) in this PR.

2022-03-23 08:34 UTC, NathalieC approved these changes

2022-03-23 08:42 UTC, tbouffard approved these changes

2022-03-23 09:15 UTC, merged