Update bpm-api.adoc
bonitasoft/bonita-doc pull request #2002
Opened 2022-03-17 10:56 UTC by vbotnari12

The page is too heavy for crawler algolia, hence we are going to split in small pages.
RUNTIME-849 : [DOC] Split BPM api page in multiple sub pages to make it indexable by algolia

2022-03-22 15:36 UTC, educhastenier commented
That would be clearer if all API pages had `api` in their name.

2022-03-22 15:41 UTC, educhastenier commented
The new pages are not in the index, is it wanted? (ie. they do not appear on the left side menu)

2022-03-23 10:51 UTC, vbotnari12 commented
> The new pages are not in the index, is it wanted? (ie. they do not appear on the left side menu)

how do we do it?

2022-03-23 11:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=2002) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=2002) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: vbotnari12<br/>:x: benjaminParisel<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-doc?pullRequest=2002) it.</sub>

2022-03-23 11:23 UTC, educhastenier commented
> > The new pages are not in the index, is it wanted? (ie. they do not appear on the left side menu)
> 
> how do we do it?

@vbotnari12 you modify taxonomy.adoc to add the new pages under bpm-api.adoc.

2022-03-23 11:25 UTC, educhastenier requested changes
remove Case from 'Case Document'

2022-03-23 11:25 UTC, educhastenier commented on modules/ROOT/pages/bpm-api.adoc
> +* xref:data-case-document-api.adoc[Data and CaseDocument]
The commonly use term is simply Document and not CaseDocument, even if the technical name of the api is caseDocument:
```suggestion
* xref:data-case-document-api.adoc[Data and Document]
```

2022-03-23 11:25 UTC, educhastenier commented on modules/ROOT/pages/data-case-document-api.adoc
> += Data and Case Document
Same remark:
```suggestion
= Data and Documents 
```

2022-03-23 13:18 UTC, vbotnari12 commented on modules/ROOT/pages/data-case-document-api.adoc
> += Data and Case Document
Done. Thanks

2022-03-27 21:14 UTC, educhastenier commented on modules/ROOT/taxonomy.adoc
> +   **** xref:data-document-api.adoc[Data and Document]
```suggestion
   **** xref:data-document-api.adoc[Data and Documents]
```

2022-03-27 21:15 UTC, educhastenier commented on modules/ROOT/pages/bpm-api.adoc
> +Documentation split :
Do we want to keep this in the page?

2022-03-27 21:15 UTC, educhastenier commented on modules/ROOT/pages/bpm-api.adoc
> +* xref:data-document-api.adoc[Data and Document]
```suggestion
* xref:data-document-api.adoc[Data and Documents]
```

2022-03-27 21:16 UTC, educhastenier approved these changes

2022-03-28 07:58 UTC, merged