feat(angularjs_18_migration): New page for AngularJS 1.8 migration
bonitasoft/bonita-doc pull request #2051
Opened 2022-05-03 09:50 UTC by jeromecambon

- In 2022.2, UID will be migrated to AngularJS 1.8
- This new page describes the impact on customer artifacts, and how to mgrate them from AngulaJS 1.3 to 1.8

2022-05-03 14:13 UTC, benjaminParisel requested changes

2022-05-03 14:13 UTC, benjaminParisel commented on modules/pages-and-forms/pages/angularjs-18-migration.adoc
> +To enable AngularJS extended support, UI Designer has been migrated to the latest AngularJS version (1.8.0).
```suggestion
To enable AngularJS extended support, UI Designer has been migrated to the latest AngularJS version (1.8.2).
```

2022-05-03 14:13 UTC, benjaminParisel commented on modules/pages-and-forms/pages/angularjs-18-migration.adoc
> +If you defined custom widgets, you should check that:
Add a sentence to explain is not an exhaustive list, but for us the most frequency issue that they could be face.

2022-05-03 14:13 UTC, benjaminParisel commented on modules/pages-and-forms/pages/angularjs-18-migration.adoc
> +* The Template does not contain `ng-messages` and `ng-messages-include` in the same `<div>` element
Adding paragraphe about https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$interpolate

2022-05-03 14:13 UTC, benjaminParisel commented on modules/pages-and-forms/pages/angularjs-18-migration.adoc
> +(extract from https://docs.angularjs.org/guide/migration[Migrating an App to a newer version])
I think we don't need to put the link on each place. We can just use extract from angularJs migration guide for example no ?

2022-05-03 14:13 UTC, benjaminParisel commented on modules/pages-and-forms/pages/angularjs-18-migration.adoc
> +* The Controller code, and the potential assets, does not contain deprecated `$http` callbacks (`$http.success` and `$http.error`)
```suggestion
* The *controller* code, and the potential assets, does not contain deprecated `$http` callbacks (`$http.success` and `$http.error`)
```

2022-05-03 14:13 UTC, benjaminParisel commented on modules/pages-and-forms/pages/angularjs-18-migration.adoc
> +* The Template does not contain `ng-messages` and `ng-messages-include` in the same `<div>` element
```suggestion
* The *template* does not contain `ng-messages` and `ng-messages-include` in the same `<div>` element
```

2022-05-03 14:23 UTC, jeromecambon commented on modules/pages-and-forms/pages/angularjs-18-migration.adoc
> +(extract from https://docs.angularjs.org/guide/migration[Migrating an App to a newer version])
Finally, to avoid ambiguity, I think it's better to keep the same name. So keeping the link seems not an issue.

2022-05-05 07:56 UTC, benjaminParisel commented
:warning: I think we can name this page angularjs-1-8-migration

2022-05-06 15:15 UTC, julienmege commented on modules/ROOT/pages/release-notes.adoc
> +Your UI Designer applications must be extensively tested to verify if any updates are required on your side to support this new version.
```suggestion
All your UI Designer artifacts must be extensively tested to verify if any updates are required on your side to support this new version.
```

2022-05-06 15:15 UTC, julienmege commented on modules/ROOT/pages/release-notes.adoc
> +UI Designer has been migrated to AngularJS 1.8, to enable AngularJS extended support.
Maybe we should point to https://xlts.dev/angularjs instead of AngularJS 1.8 ?

2022-05-06 15:15 UTC, julienmege commented on modules/pages-and-forms/pages/angularjs-1-8-migration.adoc
> += Migration to AngularJS 1.8
same here, we may should talk about XLTS

2022-05-09 09:33 UTC, jeromecambon commented on modules/ROOT/pages/release-notes.adoc
> +Your UI Designer applications must be extensively tested to verify if any updates are required on your side to support this new version.
To me they should test their application, which should indeed test all the artifacts, no?

2022-05-09 09:33 UTC, jeromecambon commented on modules/ROOT/pages/release-notes.adoc
> +UI Designer has been migrated to AngularJS 1.8, to enable AngularJS extended support.
ok

2022-05-11 07:39 UTC, merged