doc(bpmnvisu_monitoring): Update monitoring page with new BPMN visu
bonitasoft/bonita-doc pull request #2084
Opened 2022-07-15 13:14 UTC by jeromecambon

Covers [RUNTIME-1212](https://bonitasoft.atlassian.net/browse/RUNTIME-1212)

2022-07-20 09:28 UTC, abirembaut requested changes
just a few suggestions

2022-07-20 09:28 UTC, abirembaut commented on modules/runtime/pages/cases.adoc
> +On the diagram, colored flags on the steps show the number of step instances in the possible states. +
```suggestion
On the diagram, colored flags on the steps show the number of step instances in each state. +
```

2022-07-20 09:28 UTC, abirembaut commented on modules/runtime/pages/cases.adoc
> +Put your mouse hover any node to see an explanation of the display. +
```suggestion
Put your mouse hover any step to see an explanation of the display. +
```
for consistency with the previous sentence

2022-07-20 09:28 UTC, abirembaut commented on modules/runtime/pages/cases.adoc
> +//xref:ROOT:customize-display-process-monitoring.adoc[How to customize the display of process execution monitoring].
```suggestion
You can customize the diagram page, or embed the BPMN diagram in your own page: see xref:pages-and-forms:customize-display-process-monitoring.adoc[How to customize the display of process execution monitoring].
```

2022-07-20 09:28 UTC, abirembaut commented on modules/runtime/pages/monitoring.adoc
> +You can also open a diagram of a process, by clicking on the _Picture_ icon for the process. On the diagram, you can see the number and state of cases in progress at each step. +
```suggestion
You can also open the diagram of a process, by clicking on the _Picture_ icon for the process. On the diagram, you can see the number and state of cases in progress at each step. +
```

2022-07-20 09:28 UTC, abirembaut commented on modules/runtime/pages/monitoring.adoc
> +Put your mouse hover any node to see an explanation of the display. +
```suggestion
Put your mouse hover any step to see an explanation of the display. +
```

2022-07-20 09:28 UTC, abirembaut commented on modules/runtime/pages/monitoring.adoc
> +//xref:ROOT:customize-display-process-monitoring.adoc[How to customize the display of process execution monitoring].
```suggestion
You can customize the diagram page, or embed the BPMN diagram in your own page: see xref:pages-and-forms:customize-display-process-monitoring.adoc[How to customize the display of process execution monitoring].
```

2022-07-22 14:43 UTC, vbotnari12 requested changes
Please mention here about the zoom limitations with the magic mouse.

2022-07-22 15:32 UTC, merged