doc(reports) improve date_range widget documentation
bonitasoft/bonita-doc pull request #211
Opened 2016-12-01 13:58 UTC by cpuy

Add more specific details for date_range widget initial values

Closes [BS-15720](https://bonitasoft.atlassian.net/browse/BS-15720)

Once it is merged, `7.4` and `7.5` branches should be rebased onto `7.3` or `7.3` should be merged in those branches...

2017-01-25 12:34 UTC, abirembaut requested changes
LGTM (just one small note)

2017-01-25 12:34 UTC, abirembaut commented on md/create-a-report.md
> +For a **DATE\_RANGE** widget, if you name the associated parameter `p_date`, `p_date_from` and `p_date_to` initial
I would just a add a "then" to ease the understanding of the sentence (, then `p_date_from` and `p_date_to`...).

2017-01-26 09:05 UTC, cpuy commented on md/create-a-report.md
> +For a **DATE\_RANGE** widget, if you name the associated parameter `p_date`, `p_date_from` and `p_date_to` initial
ok thx

2017-01-26 09:12 UTC, cpuy commented
Done

2017-03-03 08:19 UTC, cpuy commented
Up! Up!

2017-03-14 16:15 UTC, abirembaut approved these changes

2017-03-14 16:15 UTC, merged