ci(content_linter): Enable Vale linter
bonitasoft/bonita-doc pull request #2195
Opened 2022-10-14 13:43 UTC by jeromecambon

The Vale linter checks the doc content and detect typos, incorrect grammar forms, and provide suggestions. See https://vale.sh for details.

2022-10-17 10:32 UTC, tbouffard requested changes

2022-10-17 10:32 UTC, tbouffard commented on .github/workflows/contribution-check.yml
> +      - uses: actions/checkout@v2
let's use v3

2022-10-17 10:32 UTC, tbouffard commented on .github/workflows/contribution-check.yml
> +      - id: files
```suggestion
      - id: files
        name: Detect changed files
```

2022-10-17 10:32 UTC, tbouffard commented on .github/workflows/contribution-check.yml
> +
```suggestion
```

2022-10-17 10:32 UTC, tbouffard commented on .github/styles/Vocab/Base/accept.txt
> +Asciidoc
⚠️ wrong syntax, see https://docs.asciidoctor.org/asciidoc/latest/
```suggestion
AsciiDoc
```

2022-10-17 12:35 UTC, tbouffard commented on .github/workflows/contribution-check.yml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v3
```

2022-10-17 12:37 UTC, tbouffard commented on .github/workflows/contribution-check.yml
> +      - uses: actions/checkout@v2
already applied

2022-10-17 12:49 UTC, tbouffard commented
The dictionary is now OK. I don't have time to review the rules today. I wonder if there are any configured rules that could generate false positives.
Let's wait for someone else to review.

2022-10-17 12:54 UTC, jeromecambon commented
> The dictionary is now OK. I don't have time to review the rules today. I wonder if there are any configured rules that could generate false positives.
> Let's wait for someone else to review.

The "dictionary" (accept.txt file) will evolve with time, it's just a start. We'll add new keywords when needed.
And yes, we'll have false positive. Typically when the page includes variable names, we can have many. So don't expect the check will be always green...

2022-10-17 13:09 UTC, benjaminParisel approved these changes
LGTM :clap:

2022-10-17 15:59 UTC, tbouffard approved these changes
> And yes, we'll have false positive. Typically when the page includes variable names, we can have many. So don't expect the check will be always green...

OK, that's clear. False positives are a pain and if we have too many, nobody will look at the results of the checks. Let's start with what is proposed here and see how it runs.

2022-10-20 03:42 UTC, tbouffard commented
Put in Draft as we are waiting for feedback from the Product Team.

2022-10-25 08:17 UTC, merged