SQL Server - setting presume abort for XA in-doubt transaction
bonitasoft/bonita-doc pull request #220
Opened 2017-01-19 16:25 UTC by jjargot

This is mandatory setting for all databases involved in a XA transaction: bonita engine database and business data database.

2017-01-19 16:31 UTC, educhastenier requested changes

2017-01-19 16:31 UTC, educhastenier commented on md/database-configuration.md
> +Run the script below to avoid the SQL Server change the status of the database to SUSPECT during database server startup when in-doubt XA transactions are found.
To visualize a Carriage Return character, add 2 spaces at the end of line : `  `

2017-01-26 08:37 UTC, educhastenier commented
retest this please

2017-01-26 08:38 UTC, educhastenier commented on md/database-configuration.md
> +#### Recommended configuration in-doubt xact resolution
**for** in-doubt ...

2017-01-26 08:44 UTC, educhastenier commented on md/database-configuration-for-business-data.md
> +In your RDBMS, create a database to be used to store business object. Do not reuse the Bonita BPM Engine database. Follow the instructions in the [Specific database configuration](database-configurat
This link is not valid. It must point to an Anchor `<a id="specific_database_configuration">` that must exist, and must not contain space characters.

2017-01-26 08:55 UTC, educhastenier commented on md/database-configuration-for-business-data.md
> +In your RDBMS, create a database to be used to store business object. Do not reuse the Bonita BPM Engine database. Follow the instructions in the [Specific database configuration](database-configurat
Have a look at https://github.com/bonitasoft/bonita-doc/blob/7.3/CONTRIBUTING.md for how to use anchors

2017-01-26 10:19 UTC, jjargot commented on md/database-configuration-for-business-data.md
> +In your RDBMS, create a database to be used to store business object. Do not reuse the Bonita BPM Engine database. Follow the instructions in the [Specific database configuration](database-configurat
The link was tested ok in the preview from git-hub

2017-01-26 10:20 UTC, jjargot commented on md/database-configuration.md
> +#### Recommended configuration in-doubt xact resolution
Do I need to do something ?

2017-01-31 07:42 UTC, jjargot commented
done

2017-01-31 15:15 UTC, educhastenier commented on md/database-configuration.md
> +#### Recommended configuration in-doubt xact resolution
Add the word **for**

2017-01-31 15:16 UTC, educhastenier commented
retest this please

2017-01-31 16:47 UTC, jjargot commented
The word *for* has been added

2017-01-31 16:56 UTC, jjargot commented on md/database-configuration.md
> +#### Recommended configuration in-doubt xact resolution
added

2017-01-31 16:58 UTC, educhastenier commented
Looks good to me

2017-01-31 16:58 UTC, merged