feat(properties): document how to configure Bonita with properties
bonitasoft/bonita-doc pull request #2556
Opened 2023-12-13 12:05 UTC by educhastenier

* with Setup Tool
* via Java Sysprops
* via Env vars

2023-12-13 16:37 UTC, vhemery requested changes
I can't find the configuring-bonita-with-properties.adoc from the navigation menu.
It should be added in runtime-configuration-index and in runtime-nav.adoc

Also see suggestions inline.

2023-12-13 16:37 UTC, vhemery commented on modules/runtime/pages/configuring-bonita-with-properties.adoc
> +* TODO
No TODO in the final doc site... 😉

2023-12-13 16:41 UTC, vhemery commented
> I can't find the configuring-bonita-with-properties.adoc from the navigation menu. It should be added in runtime-configuration-index and in runtime-nav.adoc
> 
> Also see suggestions inline.

Argh.. my most meaningfull comment was lost...
I was suggesting to use alternative presentation for:

- In a Linux Shell:
- When starting a Bonita Docker container:
- In a docker-compose.yml file:
See https://github.com/bonitasoft/bonita-doc/edit/feat/properties/document_bonita_properties/modules/runtime/pages/bonita-docker-installation.adoc and search for `[tabs]` for examples.

2023-12-13 20:28 UTC, educhastenier commented on modules/runtime/pages/configuring-bonita-with-properties.adoc
> +* TODO
Fixed in next commit

2023-12-13 20:49 UTC, educhastenier commented
> > I can't find the configuring-bonita-with-properties.adoc from the navigation menu. It should be added in runtime-configuration-index and in runtime-nav.adoc
> > Also see suggestions inline.
> 
> Argh.. my most meaningfull comment was lost... I was suggesting to use alternative presentation for:
> 
> * In a Linux Shell:
> * When starting a Bonita Docker container:
> * In a docker-compose.yml file:
>   See https://github.com/bonitasoft/bonita-doc/edit/feat/properties/document_bonita_properties/modules/runtime/pages/bonita-docker-installation.adoc and search for `[tabs]` for examples.

Feedbacks integrated.
Thx for the suggestions.

2023-12-14 07:03 UTC, vhemery approved these changes
Looks perfect to me

2023-12-14 07:04 UTC, merged