fix(restapi) add archived case api
bonitasoft/bonita-doc pull request #264
Opened 2017-04-13 14:26 UTC by cpuy

Add documentation for archived case context.

Closes [BS-15979](https://bonitasoft.atlassian.net/browse/BS-15979)

2017-04-20 09:48 UTC, laurentleseigneur commented
retest this please

2017-04-20 09:50 UTC, laurentleseigneur commented on md/bpm-api.md
> +      "document1_ref":{
this part seems to be the response and not the payload ?

2017-04-24 06:37 UTC, cpuy commented on md/bpm-api.md
> +      "document1_ref":{
Actually this is the response payload :-).  So i guess using payload here is right

2017-05-02 10:13 UTC, laurentleseigneur requested changes

2017-05-02 10:13 UTC, laurentleseigneur commented on md/bpm-api.md
> +      "document1_ref":{
your example is false: is name is `myBusinessDate`, reference will be `myBusinessDate_ref` in json response

2017-05-02 10:13 UTC, laurentleseigneur commented on md/bpm-api.md
> +      "document1_ref":{
see real example here:
> {
> "ss_ref": {
> "name": "ss",
> "type": "com.company.model.BusinessObject1",
> "link": "API/bdm/businessData/com.company.model.BusinessObject1/2",
> "storageId": 2,
> "storageId_string": "2"
> },
> "mydoc_ref": {
> "id": 101,
> "processInstanceId": 1002,
> "name": "mydoc",
> "author": 4,
> "creationDate": 1493717008671,
> "fileName": "doc.pdf",
> "contentMimeType": "application/octet-stream",
> "contentStorageId": "101",
> "url": "documentDownload?fileName=doc.pdf&contentStorageId=101",
> "description": "dwcxdwcxdv",
> "version": "1",
> "index": -1,
> "contentFileName": "doc.pdf"
> }
> }

2017-05-03 07:41 UTC, cpuy commented on md/bpm-api.md
> +      "document1_ref":{
That is true.
Wrong copy paste from case context.

I'll fix this section as well

2017-05-03 08:21 UTC, cpuy commented
See https://github.com/bonitasoft/bonita-doc/pull/278 to fix typos in context APIs

2017-05-04 08:08 UTC, cpuy commented
UP!

2017-05-04 08:29 UTC, laurentleseigneur approved these changes

2017-05-04 08:30 UTC, laurentleseigneur commented
don't forget to merge doc branches (->7.4,7.5,7.6)

2017-05-04 08:30 UTC, merged