fix(troubleshoot): add section on how to handle transaction isolation
bonitasoft/bonita-doc pull request #2645
Opened 2024-03-27 10:04 UTC by danila-m

Relates to [RUNTIME-1830](https://bonitasoft.atlassian.net/browse/RUNTIME-1830)
Engine PR -> https://github.com/bonitasoft/bonita-engine-sp/pull/2911

2024-04-04 08:24 UTC, tbouffard commented
⚠️ The default branch is now `2022.2`, this branch must target 2022.2

2024-04-09 08:28 UTC, educhastenier requested changes
There is a confusion between 2 different detection on the search mechanism.
Let's talk about it.

2024-04-09 08:28 UTC, educhastenier commented on modules/runtime/pages/performance-troubleshooting.adoc
> +Depending on the number of elements in the DB, those queries may take a long time to execute, thus some update may take place while performing the first query.
This is not true. In this precise case, the problem is that the count query and the search query do no match exactly, so this is a dev problem. The query has to be fixed.

2024-04-09 09:31 UTC, danila-m commented
Closing this PR
As discussed it with the relevant parties, some of the info here is incorrect, and the ticket has to be treated in another way.

2024-04-09 09:31 UTC, closed without merging