docs: update release-notes.adoc for launch
bonitasoft/bonita-doc pull request #2655
Opened 2024-04-05 11:39 UTC by marcobonita

2024-04-07 21:03 UTC, AurePellefigue reviewed
it looks good to me

2024-04-08 07:16 UTC, rbioteau commented on modules/ROOT/pages/release-notes.adoc
> +* Better platform performance thanks to the L2 Cache (Enterprise Edition only)
> Better platform performance thanks to the L2 Cache (Enterprise Edition only)

@educhastenier  Isn't the improvement about clustered L2 Cache ?

2024-04-08 07:52 UTC, educhastenier commented on modules/ROOT/pages/release-notes.adoc
> +We’re proud to announce Bonita {bonitaVersion}, the first Bonita platform release of this year!
```suggestion
We’re proud to announce Bonita {bonitaVersion}, the first major Bonita platform release of this year! 
```

2024-04-08 07:54 UTC, educhastenier commented on modules/ROOT/pages/release-notes.adoc
> +* Better platform performance thanks to the L2 Cache (Enterprise Edition only)
```suggestion
* Better platform performance thanks to the L2 Cache (Enterprise Edition only), extended to clustered environments.
```

2024-04-08 07:56 UTC, educhastenier commented on modules/ROOT/pages/release-notes.adoc
> +Bonita {bonitaVersion} introduces a new search engine algorithm on all APIs and the Bonita pages included by default on Bonita User Application, Bonita Administrator and Super Administrator Applicati
Add a link to the detailling page

2024-04-08 08:00 UTC, educhastenier requested changes
minor change requested

2024-04-08 08:56 UTC, educhastenier commented on modules/ROOT/pages/release-notes.adoc
> +Bonita {bonitaVersion} introduces a new search engine algorithm on all APIs and the Bonita pages included by default on Bonita User Application, Bonita Administrator and Super Administrator Applicati
@marcobonita Why did you resolve this comment without any change or remark?

2024-04-08 12:55 UTC, educhastenier approved these changes

2024-04-08 12:56 UTC, merged