first version of release note 7.5.0
bonitasoft/bonita-doc pull request #267
Opened 2017-04-18 14:58 UTC by philippebonita

first version to be ready for BETA program, 
may be updated and refined for GA

2017-04-18 15:24 UTC, educhastenier commented on md/release-notes.md
> +* Remove suport for Oracle Weblogic application server
sup**p**ort

2017-04-18 15:25 UTC, educhastenier commented on md/release-notes.md
> +* API removals Engine APIs have been cleaned up from some deprecated methods:
Why did you merge the title with the first sentence?

2017-04-18 15:25 UTC, educhastenier commented on md/release-notes.md
> +Bonita web tools and user interfaces are fully compatible with the Microsoft Edge and IE 11 browsers (UI Designer editor, All artefacts generated by UID (Forms, Pages, ...), Bonita Portal).
~~A~~**a**ll

2017-04-18 15:27 UTC, educhastenier commented on md/release-notes.md
> +Bonita BPM works with Single-Sign-On (SSO) solutions using SAML V2 protocol `(Teamwork edition)`
`(Teamwork, Efficiency and Performance editions)`

2017-04-18 15:28 UTC, educhastenier commented
retest this please

2017-04-18 15:30 UTC, educhastenier commented on md/release-notes.md
> +* It eases the collaboration by file exchange and reduce drastically the risk of overwrite error during import of a .bos.
reduce**s**

2017-04-18 15:31 UTC, educhastenier commented on md/release-notes.md
> +In Bonita BPM Studio, provide an editor to create the Living Application navigation without having to go on the Portal administration. This is the first step towards the full Application artefacts de
`(Efficiency and Performance editions)`

2017-04-18 15:32 UTC, educhastenier commented on md/release-notes.md
> +* Create and edit LA navigation descriptor in Studio. It is the first step to industrialization of LA.
Define LA before using it

2017-04-18 15:33 UTC, educhastenier commented on md/release-notes.md
> +New management of date and time to properly manage application used on multiple timezone. It now follows the philosophy of Java 8 date management.
application**s**

2017-04-18 15:36 UTC, educhastenier commented
General remark: sentence formulation does not seem to be consistent with the way we usually turn phrases... check with other pages

2017-04-18 16:03 UTC, philippebonita commented on md/release-notes.md
> +* Remove suport for Oracle Weblogic application server
ok

2017-04-18 16:19 UTC, laurentleseigneur requested changes

2017-04-18 16:19 UTC, laurentleseigneur commented on md/release-notes.md
> +* Create and edit LA navigation descriptor in Studio. It is the first step to industrialization of LA.
keep Living Application instead of using LA

2017-04-18 16:19 UTC, laurentleseigneur commented on md/release-notes.md
> +* can construct application navigation from inside Studio based on existing artefacts.
> existing artefacts

artefacts -> artifacts
explain also that existing means inside current workspace and not deployed on portal

2017-04-18 16:19 UTC, laurentleseigneur commented on md/release-notes.md
> +New management of date and time to properly manage application used on multiple timezone. It now follows the philosophy of Java 8 date management.
... used across ... ?

2017-04-18 16:19 UTC, laurentleseigneur commented on md/release-notes.md
> +* Benefit from the Java 8 improvement of date/time management in order to manager better timezones in UI (forms and pages). Ensure the use cases of :
to better manage

2017-04-18 16:19 UTC, laurentleseigneur commented on md/release-notes.md
> +### Full Java 8 support
in fact Java8 is now required

2017-04-18 16:19 UTC, laurentleseigneur commented on md/release-notes.md
> +Bonita web tools and user interfaces are fully compatible with the Microsoft Edge and IE 11 browsers (UI Designer editor, All artefacts generated by UID (Forms, Pages, ...), Bonita Portal).
artifacts

2017-04-18 16:19 UTC, laurentleseigneur commented on md/release-notes.md
> +* httpcore is updated to httpcore 4.4.4
check that Spring has also been updated

2017-04-19 10:07 UTC, cpuy commented on md/release-notes.md
> +* httpcore is updated to httpcore 4.4.4
Spring 4.3.7.RELEASE

2017-04-19 11:54 UTC, cpuy commented on md/release-notes.md
> +* Remove support for Intyernet Explorer 9 and 10
typo

2017-04-19 11:56 UTC, laurentleseigneur requested changes

2017-04-19 11:56 UTC, laurentleseigneur commented on md/release-notes.md
> +* Remove support for Intyernet Explorer 9 and 10
Intyernet

2017-04-19 12:31 UTC, merged