feat: adding UIB communication content (#2722 improvement)
bonitasoft/bonita-doc pull request #2733
Opened 2024-06-14 07:21 UTC by marcobonita

Content of https://github.com/bonitasoft/bonita-doc/pull/2722 + suggested changes

2024-06-18 14:58 UTC, benjaminParisel commented on modules/applications/pages/uid-applications-index.adoc
> +
As you rename this page, the :page-aliases: are mandatory and refer to the oldest page name.

```suggestion
:page-aliases: applications:custom-applications-index.adoc
```

2024-06-18 15:00 UTC, benjaminParisel commented
Are you sure about this preview ? 
![image](https://github.com/bonitasoft/bonita-doc/assets/25297128/08d74e3b-9cd5-4fd3-99a8-febf2a23668d)

2024-06-19 06:34 UTC, marcobonita commented
> Are you sure about this preview ? ![image](https://private-user-images.githubusercontent.com/25297128/340727523-08d74e3b-9cd5-4fd3-99a8-febf2a23668d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzkxNDQsIm5iZiI6MTcxODc3ODg0NCwicGF0aCI6Ii8yNTI5NzEyOC8zNDA3Mjc1MjMtMDhkNzRlM2ItOWNkNS00ZmQzLTk5YTgtZmViZjJhMjM2NjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA2MzQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OWRmZTRmNWJkMmE5YWRmMDI2ZTYzNDAzOTAxZjk5NTNlMzQzZGJkNWQzMDI4M2Y2YjU2MmVmMzI4ZjI5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.txr_1fwOquQoj6cX1OgnoJdIu6nlYaWtUtfqFGuFKv4)

Weird, this part is identical to the original file

2024-06-24 11:20 UTC, benjaminParisel approved these changes
Fine for me with syntax

2024-06-24 15:49 UTC, benjaminParisel approved these changes

2024-06-24 15:49 UTC, benjaminParisel commented on modules/ROOT/pages/release-notes.adoc
> +:description: Bonita release notes for the 2024.3 version
```suggestion
:description: Bonita release notes for the {bonitaVersion} version
```

2024-06-24 15:50 UTC, benjaminParisel commented
:warning: Waiting for surge issue resolving, to check the preview and then we can merge

2024-06-25 07:19 UTC, benjaminParisel commented
@marcobonita Il y a une erreur dans le buld qui dit ceci: 
`[06:24:05.040] FATAL (antora): Page alias cannot reference an existing page: 2024.3@bonita:applications:custom-applications-index.adoc (specified as: applications:custom-applications-index.adoc)
    source: modules/applications/pages/uid-applications-index.adoc in https://github.com/marcobonita/bonita-doc.git (branch: patch-20)`

2024-06-25 07:28 UTC, marcobonita commented
> @marcobonita Il y a une erreur dans le buld qui dit ceci: `[06:24:05.040] FATAL (antora): Page alias cannot reference an existing page: 2024.3@bonita:applications:custom-applications-index.adoc (specified as: applications:custom-applications-index.adoc) source: modules/applications/pages/uid-applications-index.adoc in https://github.com/marcobonita/bonita-doc.git (branch: patch-20)`

True, we don't need that alias anymore. I removed it

2024-06-28 14:06 UTC, rbioteau requested changes

2024-06-28 14:06 UTC, rbioteau commented on modules/applications/pages/faq.adoc
> +=== What is an advancedApplication?
```suggestion
=== What is an `applicationLink` ?
```

2024-06-28 14:11 UTC, rbioteau approved these changes

2024-06-28 14:12 UTC, merged