fix(getting-started): use date only type instead of date
bonitasoft/bonita-doc pull request #274
Opened 2017-04-26 11:20 UTC by amottier

Starting with version 7.5.0 getting started tutorial need to use the new date only time as in this use case we only care about day, month and year information.
Update also includes change around auto-generation of forms that include now by default the form container.

Closes [BS-16535](https://bonitasoft.atlassian.net/browse/BS-16535)

2017-04-27 10:16 UTC, educhastenier commented on md/getting-started-tutorial.md
> -This name is used in Bonita BPM to identify the page. It is not displayed to the application user.
Double spaces at end of line means "carriage return".
Did you really mean to remove all these?

2017-04-27 11:06 UTC, abirembaut commented on md/getting-started-tutorial.md
> -This name is used in Bonita BPM to identify the page. It is not displayed to the application user.
FYI, the result: http://doc.rd.lan:50274/7.5?page=getting-started-tutorial

2017-04-27 11:51 UTC, amottier commented on md/getting-started-tutorial.md
> -This name is used in Bonita BPM to identify the page. It is not displayed to the application user.
Nope, that was a mistake. Thanks for the review. I'll fix that.

2017-04-27 12:21 UTC, amottier commented on md/getting-started-tutorial.md
> -This name is used in Bonita BPM to identify the page. It is not displayed to the application user.
Should be ok now. Still it seems that line break are ignore for content within a list (not a new issue).

2017-05-11 08:57 UTC, abirembaut reviewed
Just a few comments. Other than that it looks good to me. Good job !

2017-05-11 08:57 UTC, abirembaut commented on md/getting-started-tutorial.md
> +3. Click **_Takes value of_** link. This opens a popup listing the available operations. Choose **_Use a Java method_**. The popup displays a list of available methods. Click **_setStatus(String) - v
I'd say "Click **the** **_Takes value of_** link", but that's just me quibbling

2017-05-11 08:57 UTC, abirembaut commented on md/getting-started-tutorial.md
>  When you create your own forms, you will add this information, so that the manger can see the details of the request before approving or refusing it.
so that the **manager**

2017-05-11 08:57 UTC, abirembaut commented on md/getting-started-tutorial.md
> +   | Departure date  | Date  | request.departureDate | date  |yes  |
Technically, the widget name is Date picker

2017-05-11 08:57 UTC, abirembaut commented on md/getting-started-tutorial.md
> +    | Hidden  | `formInput.status === 'approved'` (first click on "fx"/"bind" icon) |
I would say : 
click on the "fx" binding icon first

2017-05-11 08:57 UTC, abirembaut commented on md/getting-started-tutorial.md
> +    | Available values (click on the binding "fx" icon next to the value first) | statusValues  |
click on the "fx" binding icon [next to the input field] first

2017-05-11 08:57 UTC, abirembaut commented on md/getting-started-tutorial.md
> +Once process is finished you can see the request information as stored in the test database in Bonita Studio:
Is "test database" a term we use in the rest of the documentation ?
I would rather say "development database", but I am not sure

2017-05-11 08:57 UTC, abirembaut commented on md/getting-started-tutorial.md
> +1. From the menu bar, choose **Development** menu, choose **Business Data Model**, and then choose **Brows data (h2 console)...**. This opens the h2 (test database) web interface in a web browser.
(development database) administration interface ?

2017-05-23 12:46 UTC, abirembaut requested changes
LGTM
Just one typo

2017-05-23 12:46 UTC, abirembaut commented on md/getting-started-tutorial.md
> +    | Available values (click on the "fx" binding icon next to the to the input field first) | statusValues  |
"to the" is repeated twice

2017-05-23 13:04 UTC, abirembaut approved these changes

2017-05-23 13:04 UTC, merged