feat(dates and times) Add HowTo for dates and times management
bonitasoft/bonita-doc pull request #275
Opened 2017-04-26 16:11 UTC by abirembaut

- Create a HowTo for the 3 date-times- use cases supported in 7.5
- Add the HowTo to the taxonomy

Closes [BS-16513](https://bonitasoft.atlassian.net/browse/BS-16513)

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +
It also works for pages and we mostly use "manage" throughout the product, so maybe "How to manage dates and times in BDM and User Interfaces".

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +:::
In "How to create unique task names for the user task list", we applied the same content as a note. I'd suggest we keep it as a note, but if you're more on the warning side, just change it also to the other howto.
::: info
This howto applies to Bonita BPM 7.5.0 and above.
:::

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +For use cases involving dates and times Bonita BPM comes with 3 types of data which you can manipulate through the processes, APIs and forms/pages.
since the title talks about BDM and User interfaces, we should reuse it here. I did for user interfaces, can you do it too for BDM (link API and BDM, basically).
"For use cases involving dates and times management, Bonita BPM comes with 3 types of data that you can manipulate through processes, APIs and user interfaces (forms/pages). "

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +This page gives a step by step procedure for creating a process with forms allowing to choose a date (with or without a time) and display it in another step leveraging each of these data types.
This page gives a step-by-step procedure to create a process with forms that allow to choose a date (with or without a time) and then display it, leveraging each of these data types.

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +The storage format for this type is an ISO 8601 formatted Character String (e.g. "2017-01-13").
I just copy/paste what is already in the Studio, so we always say it the same.
"DATE ONLY is used to hold a date with no time of the day. Use it for birth dates for example.
It is stored in the database as a String using ISO-8601 "yyy-mm-dd". It uses java.time.LocalDate as Java type."
Please tell us if this is not correct as it is and we will make it more accurate in the Studio.

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* In the studio, start by opening the business data model editor (Menu "Business Data Model" > "Manage...")
BDM has become a marketing term, so upper case is best (...)
To point to labels of the product, Chris used  bold.
(To point to texts written by the user, she used italic.)
+* In the studio, start by opening the Business Data Model editor (in menu **Develoment** > **Business Data Model** > **Manage...**)

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Then, in the process data tab, create a new business variable of the type of your business object
Whenever possible, use numbered list for a sequence of actions
1. Create the **business object** _Employee_ with an attribute _birthdate_ of type _DATE ONLY_
2. Create a new process
3. In the process **Data** tab, create a new **business variable** _myEmployee_ of the type _Employee_

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +
Globally, the howto could benefit from a real use case scenario, where you create a process that has a meaning, like what we asked the testers to do: 
Use case 1: instantiation = an employee enters a name and a birth date in a form, step 1 = list employees' names and birth dates in a table
Use case 2: instantiation = an employee enters opening days and times of an office (why not), step 1 = another employee from another time zone sees the opening days and times.
Use case 3: instantiation = an employee sets a meeting title, day and time, step 1= another employee from another time zone sees the meeting title, day and time in his time zone.

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +
numbered list

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* In the process/task execution tab > contract section, define the contract inputs using the Add from data... button
In the process/task **Execution** tab > **Contract** section, define the contract inputs using the **Add from data...** button

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Select the business variable you created previously
Select the business variable _myEmployee_

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +### Define the contract and task operations or business variable initialization script
As a step by step, you need to write a first paragraph for initialization, and another one for update

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Follow the steps to generate a contract with a COMPLEX input containing a DATE ONLY attribute (keep the option to generate the variable initialization script or the operations (for a task) automati
same here, as a step-by-step procedure, you need to describe both in a sequence

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Generate the UI designer form by clicking on edit in the form section of the process/task execution tab
We agreed on "UI Designer", with capital "D". Let's keep it :D 
Again, you'll need to describe both in a sequence: instantiation, then update

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +There is nothing else to do.
yes there is: look at this beautiful icon and widget!! :]

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +In order to do that:
numbered list

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Create a new task after the existing one
in the step-by-step, we should use the instantiation form and not a task, so Dave gets the best practice

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Generate its form by clicking on edit in the form section of the task execution tab
use the "where, what, how" sequence:
In the task **Execution** tab, **Form** section, generate the form by clicking on the **pencil** icon

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +The value returned by the REST API will be an ISO 8601 formatted String.
"ISO 8601-formated String"

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Set the date picker value with the variable you just created
Then:
1. From the **Form editor** palette, drop a **Date picker** widget into the whiteboard
2. Set the property **Read-only** to _yes_
3. Set its **Value** with the variable _birthDate_

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Replace the text widget value with an expression using the uiDate filter to format the date the way you want. E.g., `{{employee.birthDate | uiDate:'MM/dd/yyyy'}}` (see the embedded documentation fo
1. Drop a **Text** widget into the whiteboard
2. Replace the default **Value** property with an expression using the _uiDate_ filter to format the date the way you want. E.g., `{{employee.birthDate | uiDate:'MM/dd/yyyy'}}` 
For more information on the different formats, see the embedded documentation about filters.

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +The storage format for this type is an ISO 8601 formatted Character String (e.g. "2017-01-13T13:00:00").
+**DATE-TIME (NO TZ)** is used to hold a date-time that displays the same whatever the users' time zone (NO Time Zone). Use it for stores opening hours for exemple. 
It is stored in the database as a String using ISO 8601 "yyyy-mm-ddThh:mm:ss:sss". It uses java.time.LocalDateTime as Java type.

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +## Date and time without time zone
you can apply all comments on the following two use-cases

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +
Add the fact that the portal doesn't use those types yet but that this is work in progress.

2017-04-27 14:33 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Create an object with an attribute of type DATE ONLY
It is useful to explain in a short sentence that this type replaces DATE and why not to use DATE (NOT RECOMMENDED) anymore.

2017-04-28 07:20 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +The value returned by the REST API will be an ISO 8601 formatted String.
It would be nice to be able to copy/paste the value. Maybe we can add the value to the text before the picture

2017-04-28 07:20 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* In the UI Designer, you need first to define a new variable of type external API to retrieve the object containing the date attribute using the context:
Now in the UI Designer, define a variable to retrieve the object containing the date attribute, using the **context**:
1. In the **Variables** panel at the bottom of the editor, click on **Create a new variable** button
2. Enter the **Name** _employee_
3. Select the **Type** _External API_ 
4. Enter the following **Value**:

2017-04-28 07:20 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +* Drop a date time picker widget in the page and configure it not to handle time zone
1. Drop a **DATE TIME PICKER** widget onto the form
2. Set the property **Handle time zone** to _no_.

2017-04-28 07:20 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +![REST API request](images/dates-management-tutorial/tuto-dates-api-request.png) <!--{.img-responsive .img-thumbnail}-->
The content should reflect the departure time use case

2017-04-28 07:20 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +![REST API request](images/dates-management-tutorial/tuto-dates-api-request.png) <!--{.img-responsive .img-thumbnail}-->
The example here should reflect the use case

2017-04-28 07:20 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +Unless the user is in the GMT time zone, there will be an offset between the time he selects and the
Missing end of sentence

2017-04-28 10:02 UTC, NathalieC commented on md/taxonomy.md
> +  * [How to work with dates and times in forms and BDM](datetimes-management-tutorial.md)
Usually, for the sake of visibility, we don't write "how to" in the taxonomy
"Manage dates and times in BDM and User Interfaces"

2017-05-02 15:09 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +The storage format for this type is an ISO 8601 formatted Character String (e.g. "2017-01-13").
Ok for the first and third sentence, but for the second, I would rather write
"It is stored in the database **as an ISO-8601 formated Character String** (e.g. "2017-01-13")"
Or
"using **the** using ISO-8601 "yyyy-mm-dd" **format**"

2017-05-04 17:12 UTC, abirembaut commented
Feedback integrated
TODO: update (or drop) screenshots for the datetime examples

2017-05-05 15:01 UTC, benjaminParisel commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.employee_ref.link}`
remove the } after employee_ref.link

2017-05-09 08:04 UTC, benjaminParisel commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.flight_ref.link}`
same here

2017-05-09 08:04 UTC, benjaminParisel commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.flight_ref.link}`
same here

2017-05-09 12:39 UTC, benjaminParisel commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.employee_ref.link}`
remove }

2017-05-09 12:41 UTC, benjaminParisel commented on md/datetimes-management-tutorial.md
> +The type **DATE-TIME (NO TIME ZONE)** is used to hold a date-time that display the same whatever the users' time zone is. It can be used it for stores opening hours for example.
replace user**s'** time zone by user**'s** time zone no ?

2017-05-09 12:50 UTC, benjaminParisel commented on md/datetimes-management-tutorial.md
> +The type **DATE-TIME (TZ)** is used to hold a date-time which displayed value should adapt to the user time zone (e.g., the day and time of a meeting with participants from multiple time zones).
Repalce TZ by TIME ZONE

2017-05-09 14:39 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.employee_ref.link}`
fixed

2017-05-09 14:39 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.flight_ref.link}`
fixed

2017-05-09 14:39 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.flight_ref.link}`
fixed

2017-05-09 14:39 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.employee_ref.link}`
fixed

2017-05-09 14:39 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +The type **DATE-TIME (NO TIME ZONE)** is used to hold a date-time that display the same whatever the users' time zone is. It can be used it for stores opening hours for example.
fixed

2017-05-09 14:40 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +The type **DATE-TIME (TZ)** is used to hold a date-time which displayed value should adapt to the user time zone (e.g., the day and time of a meeting with participants from multiple time zones).
fixed

2017-05-09 14:40 UTC, abirembaut commented
feedback integrated

2017-05-12 14:59 UTC, lio-p commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.employee_ref.link`
Change `../{{context}}.employee_ref.link`   by `../{{context.employee_ref.link}}`. Doesn't work otherwise.

2017-05-12 15:00 UTC, lio-p requested changes

2017-05-12 15:00 UTC, lio-p commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.employee_ref.link`
Change `../{{context}}.employee_ref.link`   by `../{{context.employee_ref.link}}`. Doesn't work otherwise.

2017-05-12 15:13 UTC, lio-p commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.flight_ref.link`
Change ../{{context}}.flight_ref.link by ../{{context.flight_ref.link}}. Doesn't work otherwise.

2017-05-12 15:13 UTC, lio-p commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.flight_ref.- Update Restlet to latest version`
Change ../{{context}}.flight_ref.link by ../{{context.flight_ref.link}}. Doesn't work otherwise.

2017-05-12 15:14 UTC, lio-p commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.meeting_ref.link`
Change ../{{context}}.meeting_ref.link by ../{{context.meeting_ref.link}}. Doesn't work otherwise.

2017-05-12 15:14 UTC, lio-p commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.meeting_ref.link`
Change ../{{context}}.meeting_ref.link by ../{{context.meeting_ref.link}}. Doesn't work otherwise.

2017-05-15 09:20 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.employee_ref.link`
Well spotted !
Fixed

2017-05-15 09:20 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.employee_ref.link`
Fixed

2017-05-15 09:20 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.flight_ref.link`
Fixed

2017-05-15 09:20 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.flight_ref.- Update Restlet to latest version`
Fixed

2017-05-15 09:20 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.meeting_ref.link`
Fixed

2017-05-15 09:20 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Set the **API URL** of the variable to `../{{context}}.meeting_ref.link`
Fixed

2017-05-15 09:31 UTC, abirembaut commented
Fixed API URL expression
link to the howto in the widet spage

2017-05-15 15:03 UTC, julienmege commented
retest this please

2017-05-15 15:42 UTC, tnguyen1 commented
retest this please

2017-05-17 12:22 UTC, abirembaut reviewed
LGTM, just a few notes

2017-05-17 12:22 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +To manage dates and times management in the BDM and User Interfaces, Bonita BPM comes with 3 types of data that you can manipulate through processes, APIs and user interfaces (forms/pages).
I believe "management" should be removed

2017-05-17 12:22 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +2. Since you have a **DATE ONLY** attribute in the contract inputs, a **Date picker** widget is automatically added to the form
Markdown will increment the numbers correctly if you leave "1." for each bullet point of the numbered list which makes it easer to maintain the list if you just want to insert or remove an item

2017-05-17 12:22 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +However, to support backward compatibility, the output of the widget is always a Javascript Date object. So it will change the type of the variable bound to the widget **Value** to a Date object when
"to support backward compatibility" doesn't sound good to me. I would rather say "to be backward compatible" or "to support pages designed with older UI Designer version"

2017-05-17 12:28 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +2. Since you have a **DATE ONLY** attribute in the contract inputs, a **Date picker** widget is automatically added to the form
anyway, it will still work if you write:
`1.
3.`
So it does not really matter

2017-05-18 04:42 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +To manage dates and times management in the BDM and User Interfaces, Bonita BPM comes with 3 types of data that you can manipulate through processes, APIs and user interfaces (forms/pages).
you're right. Thanks

2017-05-18 04:43 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +2. Since you have a **DATE ONLY** attribute in the contract inputs, a **Date picker** widget is automatically added to the form
I should have checked on the real page. thanks

2017-05-18 04:44 UTC, NathalieC commented on md/datetimes-management-tutorial.md
> +However, to support backward compatibility, the output of the widget is always a Javascript Date object. So it will change the type of the variable bound to the widget **Value** to a Date object when
ok, picked the second option

2017-05-18 08:23 UTC, abirembaut reviewed
Great !
Just 2 comments.And I will put the numbered list back with the "1." only for consistency

2017-05-18 08:23 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +The type **DATE-TIME (TIME ZONE)** is used to hold a date-time that whose displayed value should adapt to the user's time zone (e.g., the day and time of a meeting with participants from multiple tim
remove the "that" : 
"date-time whose displayed value"

2017-05-18 08:23 UTC, abirembaut commented on md/datetimes-management-tutorial.md
> +1. Update the variable *formOutput*  to change its value to:
whitespace to remove before "to change"

2017-05-18 08:55 UTC, merged