feat: add a new UIB guide on how to handle pagination
bonitasoft/bonita-doc pull request #2759
Opened 2024-07-02 07:25 UTC by marcobonita

2024-07-02 07:58 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +    - `Value`: {{List1.pageNo-1}}
```suggestion
    - `Value`: {{(List1.pageNo-1)}}
```

2024-07-02 07:59 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +    - `Key`: s
If you want to focus on pagination the `s` parameter can be omitted in this guide.

2024-07-02 08:02 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +
```suggestion

INFO: All Bonita API calls returning a collection of elements are paginated and their response contains a https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range[Content-Range header].

```

2024-07-02 08:03 UTC, rbioteau reviewed
Note that this guide is specific to how server side pagination is done with Bonita API.

2024-07-04 13:16 UTC, rbioteau requested changes
Remove input widget

2024-07-04 13:16 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +Configure the input widget:
This can be removed. Input widget is used for filtering the list which is not part of this guide

2024-07-04 13:16 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +    - `Value`: {{(List1.pageNo-1)}}
Maybe using relevant Widget name (eg: `UserList`) can facilitate the comprehension and push for good practice.

2024-07-04 13:16 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +INFO: All Bonita API calls returning a collection of elements are paginated and their response contains a https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range[Content-Range header]
```suggestion
NOTE: All Bonita API calls returning a collection of elements are paginated and their response contains a https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range[Content-Range header].
```

2024-07-04 13:35 UTC, marcobonita commented on modules/applications/pages/how-to-handle-pagination.adoc
> +Configure the input widget:
Hi @rbioteau, I think it's still valuable to keep the input widget part. It shows how widgets can easily interact together.
The purpose of this tutorial is more than only handling pagination, it's also about building a coherent interface with interactions

2024-07-05 11:56 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +    - `Value`: {{(List1.pageNo-1)}}
```suggestion
    - `Value`: {{(UserList.pageNo-1)}}
```

2024-07-05 11:56 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +    - `Value`: {{List1.pageSize}}
```suggestion
    - `Value`: {{UserList.pageSize}}
```

2024-07-05 11:57 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +    - `Value`: {{Input1.text}}
```suggestion
    - `Value`: {{UserFilterInput.text}}
```

2024-07-05 11:57 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +On the interface, drag and drop an input widget (Input1) and a list widget (List1).
```suggestion
On the interface, drag and drop an input widget (rename it UserFilterInput) and a list widget (rename it UserList).
```

2024-07-05 12:00 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +Go to the `Queries` tab and create a request that will adapt the pagination depending on what is typed in an input widget:
```suggestion
Go to the `Queries` tab and create a request that will fetch users using server side pagination and filter users depending on a search term typed in an input widget:
```

2024-07-05 12:13 UTC, rbioteau commented on modules/applications/pages/how-to-handle-pagination.adoc
> +On the interface, drag and drop an input widget (rename it UserFilterInput`) and a list widget (rename it `UserList`).
```suggestion
On the interface, drag and drop an input widget (rename it `UserFilterInput`) and a list widget (rename it `UserList`).
```

2024-07-05 12:15 UTC, rbioteau approved these changes

2024-07-05 12:15 UTC, merged