docs(uib): retrieve user avatar icon
bonitasoft/bonita-doc pull request #2823
Opened 2024-08-26 15:10 UTC by VishalThapaliya

2024-08-27 05:04 UTC, marcobonita requested changes

2024-08-27 05:04 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-retrieve-user-avatar.adoc
> += Retrieve user avatar image
```suggestion
= Use JS to retrieve user avatar image
```

2024-08-27 05:04 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-retrieve-user-avatar.adoc
> +* Next, drag and drop a `list` widget onto the interface and bind it to the `getUsers` query that was created earlier.
```suggestion
* Next, drag and drop a `list` widget onto the interface and bind it to the `getUsers` query that was created earlier:
```

2024-08-27 05:04 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-retrieve-user-avatar.adoc
> +* Select a text widget and bind it to the `firstname` of a user in the list. For instance, use `First name {{ currentItem.firstname }}`.
```suggestion
* Select a text widget and bind it to the `firstname` of a user in the list. For instance, use `First name {{ currentItem.firstname }}`:
```

2024-08-27 05:04 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-retrieve-user-avatar.adoc
> +For example, user `{{ userAvatar.getIconFullURL(currentItem.icon) }}`.
```suggestion
For example, user `{{ userAvatar.getIconFullURL(currentItem.icon) }}`:
```

2024-09-03 08:27 UTC, Shmayro approved these changes
lgtm

2024-09-03 08:28 UTC, merged