docs: How to make a contract with a multiple attribute
bonitasoft/bonita-doc pull request #2909
Opened 2024-11-25 10:04 UTC by jeromecambon

Covers [BPM-321](https://bonitasoft.atlassian.net/browse/BPM-321)

2024-11-25 13:42 UTC, AleRondon commented
Feedback after using the described procedure in [Invoice Management App](https://github.com/bonitasoft-presales/uib_InvoiceManagement/)

1. **Impossible to start with no contact**: The described documentation requires to start with an existing contact / placeholder, which might be confusing for some users. Should be able to have an empty array and create a new line with the required attributes.
2. **Update function**: Updating a contact just erases and create a new one which can lead to next issue.
3. **ID management errors**: ID can be duplicated if deleting a contact and recreating a new one, which can then cause errors when deleting or updating a contact.

![image](https://github.com/user-attachments/assets/b703ec07-108b-412f-a03c-dd624806a42e)

2024-11-25 13:59 UTC, marcobonita requested changes

2024-11-25 13:59 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-contract-with-multiple-attribute.adoc
> +Creating a UI to start a Process Instance, you will need a UI interface that allows the user to create a new Provider and add multiple Contacts.
```suggestion
To start a Process Instance, the UI should allow users to create a new Provider and add multiple Contacts.
```

2024-11-25 13:59 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-contract-with-multiple-attribute.adoc
> +Go to the `JS` tab and create a new JS Object called `contactsHandler` and copy and paste the following code:
```suggestion
Go to the `JS` tab and create a new JS Object called `ContactsHandler` and copy and paste the following code:
```

2024-11-25 13:59 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-contract-with-multiple-attribute.adoc
> +* Set the `Title` column as `Select` and set the `Options` property as `{{ContactsHandler.getTitleTypes.data}}`
```suggestion
* Set the `Title` column type as `Select` and set the `Options` property as `{{ContactsHandler.getTitleTypes.data}}`
```

2024-11-25 13:59 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-contract-with-multiple-attribute.adoc
> +* Set the `ContactType` column as `Select` and set the `Options` property as `{{ContactsHandler.getContactTypes.data}}`
```suggestion
* Set the `ContactType` column type as `Select` and set the `Options` property as `{{ContactsHandler.getContactTypes.data}}`
```

2024-11-25 13:59 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-contract-with-multiple-attribute.adoc
> +    ** Set the `Column type` as `delete` icon
```suggestion
    ** Set the `Column type` as `icon button`
```

2024-11-25 15:17 UTC, jeromecambon commented
> Feedback after using the described procedure in [Invoice Management App](https://github.com/bonitasoft-presales/uib_InvoiceManagement/)
> 
> 1. **Impossible to start with no contact**: The described documentation requires to start with an existing contact / placeholder, which might be confusing for some users. Should be able to have an empty array and create a new line with the required attributes.
> 2. **Update function**: Updating a contact just erases and create a new one which can lead to next issue.
> 3. **ID management errors**: ID can be duplicated if deleting a contact and recreating a new one, which can then cause errors when deleting or updating a contact.
> 
> ![image](https://private-user-images.githubusercontent.com/45388095/389550207-b703ec07-108b-412f-a03c-dd624806a42e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDgwNjAsIm5iZiI6MTczMjU0Nzc2MCwicGF0aCI6Ii80NTM4ODA5NS8zODk1NTAyMDctYjcwM2VjMDctMTA4Yi00MTJmLWEwM2MtZGQ2MjQ4MDZhNDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE1MTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjODhkMjVhOTE2YjdmNmJiZTQ2NGQ2NDcxNGU1MDdlMjViNWE2MWZmNDY0ZjNhZTBmNzk5M2Y3YmJjZGIwZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UlAeevXsg5xZXv2XGev-BqdHzYOSyriSYE03Q5EJguI)



> Feedback after using the described procedure in [Invoice Management App](https://github.com/bonitasoft-presales/uib_InvoiceManagement/)
> 
> 1. **Impossible to start with no contact**: The described documentation requires to start with an existing contact / placeholder, which might be confusing for some users. Should be able to have an empty array and create a new line with the required attributes.
> 2. **Update function**: Updating a contact just erases and create a new one which can lead to next issue.
> 3. **ID management errors**: ID can be duplicated if deleting a contact and recreating a new one, which can then cause errors when deleting or updating a contact.
> 
> ![image](https://private-user-images.githubusercontent.com/45388095/389550207-b703ec07-108b-412f-a03c-dd624806a42e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDgwODgsIm5iZiI6MTczMjU0Nzc4OCwicGF0aCI6Ii80NTM4ODA5NS8zODk1NTAyMDctYjcwM2VjMDctMTA4Yi00MTJmLWEwM2MtZGQ2MjQ4MDZhNDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE1MTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZTc2YTBlNWJjZjFhYTQ4ZDVmYWYyNDZjY2U1OTliOWRjZDUzMGZlOTFjMTRmZGIwNTJmNWM1YzEzMmUwNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._TO5rsr4N1qVLu26jc4gOljn_IWXVE05rlN5E_6hBXk)

I have updated the JS code to make it work correctly, without initial contact.

2024-11-25 15:47 UTC, marcobonita commented
@jeromecambon could we elaborate a little bit on the purpose of this guide? 

For example the introduction "With Bonita, you can create a contract with a multiple attribute. For example, a provider may have multiple contacts." could use a little bit more details. It doesn't seem really clear to me for now

2024-11-25 16:55 UTC, AleRondon commented
The ID issues (to create, update and delete users) has been tested and fixed on my application
For the empty contact, maybe it will be best to leave an example/placeholder, to avoid having an empty table without columns or any other strange behaviour

2024-11-26 15:56 UTC, marcobonita approved these changes

2024-11-26 16:00 UTC, benjaminParisel approved these changes

2024-11-26 16:02 UTC, merged