docs: Upload and view a document
bonitasoft/bonita-doc pull request #2911
Opened 2024-11-26 14:47 UTC by jeromecambon

Covers [BPM-320](https://bonitasoft.atlassian.net/browse/BPM-320)

2024-11-26 16:28 UTC, AleRondon commented
Can we see an example of how to configure this document in a body for an instantiation call for example?
![image](https://github.com/user-attachments/assets/52c958eb-178e-4c34-921b-09f0a709e7ae)

2024-11-26 17:30 UTC, AleRondon commented
Can we please add an example on how to use the file viewer for a document with the information provided by the task context?

![image](https://github.com/user-attachments/assets/1df97a4f-a501-4933-b10f-3247386b329d)

2024-11-27 09:47 UTC, marcobonita requested changes
Typos and rephrasing

2024-11-27 09:47 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-handle-document.adoc
> +If you want to select a document from your computer and upload it to your Bonita application, you can use the `FilePicker` widget, and the Bonita's `formFileUpload` API.
```suggestion
If you want to select a document from your computer and upload it to your Bonita application, you can use the `FilePicker` widget along with the Bonita's `formFileUpload` API.
```

2024-11-27 09:47 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-handle-document.adoc
> +The DocumentViewer widget allows you to view the uploaded document.
```suggestion
The `DocumentViewer` widget allows you to view the uploaded document.
```

2024-11-27 09:47 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-handle-document.adoc
> += Handle a document
```suggestion
= Upload and view documents
```

2024-11-27 09:47 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-handle-document.adoc
> +You can now display the document name in a text widget. Drag and drop a Text widget onto your interface and
```suggestion
You can now display the document name in a `Text` widget. Drag and drop a `Text` widget onto your interface and
```

2024-11-27 09:47 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-handle-document.adoc
> +set the `Text` property to `{{JSON.parse(uploadDocument.data).filename}}`.
```suggestion
set its `Text` property to `{{JSON.parse(uploadDocument.data).filename}}`.
```

2024-11-27 09:47 UTC, marcobonita commented on modules/applications/pages/ui-builder/how-to-handle-document.adoc
> +Note the `JSON.parse()` call that allow to transform the response (string) into a JSON object.
```suggestion
Note the `JSON.parse()` call, which transforms the response (string) into a JSON object.
```

2024-12-03 09:17 UTC, jeromecambon commented
> Can we please add an example on how to use the file viewer for a document with the information provided by the task context?
> 
> ![image](https://private-user-images.githubusercontent.com/45388095/390080304-1df97a4f-a501-4933-b10f-3247386b329d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTE0NzIsIm5iZiI6MTczMjc5MTE3MiwicGF0aCI6Ii80NTM4ODA5NS8zOTAwODAzMDQtMWRmOTdhNGYtYTUwMS00OTMzLWIxMGYtMzI0NzM4NmIzMjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDEwNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMWM1ZTA2ZDg2NzAyNWY0MTEwMzQzOWI4N2NmMjRjYTM4Yjg0ZmQ5YmQzYzkyN2I3ZTA5OTBmYTA4ZWFiYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MG4QcOeazBTSoY6aTBjArbCa79xUlN-e6JInxQnwBR4)

I succeeded to upload the document as base64, access it via a Bonita task, and view it in the DocumentViewer widget. However, the document is not viewable by UID widget (in the admin app for example), which requires a binary format.
I didn't succeed to upload the document as binary, and encode it as base64 to make it readable by the widget. I encoded as base64, but I still have a blank result on the widget...
I propose to merge this PR, since it add some interesting values. We can handle the issue separately.

2024-12-03 09:32 UTC, marcobonita approved these changes

2024-12-04 09:46 UTC, benjaminParisel approved these changes

2024-12-04 14:02 UTC, merged