doc : Autocomplete widget does not update its displayed value
bonitasoft/bonita-doc pull request #2946
Opened 2024-12-19 10:32 UTC by jeromecambon

Covers [UID-733](https://bonitasoft.atlassian.net/browse/UID-733)

2024-12-19 15:44 UTC, benjaminParisel commented
![image](https://github.com/user-attachments/assets/385be0ef-6aaa-468b-ad3b-e1fd103f699e)

I am not satisfied with the result. I suggest to move the troubleshooting section in the dedicated widget part.

I push a commit to do it, feel free to rollback if you think it's better before.

2024-12-19 16:32 UTC, jeromecambon commented
I think that including the troubleshooting in the widget description make the page less readable, and would "pollute" the widget descriptions. However, adding a pointer from the widget description to the dedicated troubleshooting (if any) would provide a good alternative. What do you think?

2024-12-20 08:35 UTC, benjaminParisel commented
> @benjaminParisel I think that including the troubleshooting in the widget description make the page less readable, and would "pollute" the widget descriptions. However, adding a pointer from the widget description to the dedicated troubleshooting (if any) would provide a good alternative, and avoid to miss it. What do you think?

Do what you think is better and more readable but please, don't put three troubleshooting titles and icon (like we can see on the screen)

2024-12-20 09:09 UTC, jeromecambon commented
> > @benjaminParisel I think that including the troubleshooting in the widget description make the page less readable, and would "pollute" the widget descriptions. However, adding a pointer from the widget description to the dedicated troubleshooting (if any) would provide a good alternative, and avoid to miss it. What do you think?
> 
> Do what you think is better and more readable but please, don't put three troubleshooting titles and icon (like we can see on the screen)

I kept the same formatting already in place, but yes we should use the example we provided here: https://bonitasoft.github.io/bonita-documentation-theme/troubleshooting.html

2024-12-20 09:51 UTC, benjaminParisel requested changes

2024-12-20 09:51 UTC, benjaminParisel commented on modules/pages-and-forms/pages/widgets.adoc
> +See [#Troubleshooting UI Designer widgets] to solve common issues with this widget.
```suggestion
See <<troubleshooting-ui-designer-widgets>> to solve common issues with this widget.
```

Example could be found here, https://bonitasoft.github.io/bonita-documentation-theme/links.html#_anchors_to_navigate_inside_the_same_document

2024-12-20 09:56 UTC, benjaminParisel approved these changes

2024-12-20 09:56 UTC, merged