fix(engine sequence): improve BPM execution sequence
bonitasoft/bonita-doc pull request #299
Opened 2017-05-17 15:49 UTC by educhastenier

Closes [BS-16222](https://bonitasoft.atlassian.net/browse/BS-16222)

2017-05-18 12:22 UTC, rbioteau requested changes

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +   **Community**:    Execution duration is not limited. If the connector never finishes, the process instantiation will never finish
trim spaces

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +   the connector execution is aborted and the process instantiation is considered failed.
remove linebreak

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +1. The Engine executes actor filters and then potentially assigns the task to a user
2.

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +1. The Engine launches the "on enter" connectors
3.

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +1. The Engine evaluates the task dynamic name and description. This will be evaluated only once
4.

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +1. The user enters data in the form
2.

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +1. The button of the form having the **Submit task** action in the **UI designer** sends a POST request with the form data to start the step
etc...

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +1. Find the next state of the flow node and set it as the current state.
2.

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +  1. If the state is neither stable nor terminal, the transition to the next state is scheduled asynchronously.
2.

2017-05-18 12:22 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
> +1. When a connector execution is finished, if there are other connectors, they are executed in the same way. If there are no more connectors, the Engine continues to execute the state's behavior by t
2.

2017-05-18 15:56 UTC, educhastenier commented on md/execution-sequence-states-and-transactions.md
> +1. The Engine executes actor filters and then potentially assigns the task to a user
no need for numbering to work, and that allows the reordering of the lines without the need for re-number them

2017-05-18 15:58 UTC, educhastenier commented on md/execution-sequence-states-and-transactions.md
> +   the connector execution is aborted and the process instantiation is considered failed.
The linebreak is here for lisibility when editing the code.
Having lines of 2000 characters is counter-productive.

2017-05-18 15:59 UTC, educhastenier commented
retest this please

2017-05-19 07:47 UTC, rbioteau requested changes

2017-05-19 07:47 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
>  6. Process data instances are created and initialized in the order of declaration using
add a `:`

2017-05-19 07:47 UTC, rbioteau commented on md/execution-sequence-states-and-transactions.md
>    * An **operation** declared on the process that saves its value to the process data
indent bullet points

2017-05-19 08:27 UTC, rbioteau approved these changes

2017-05-19 08:27 UTC, merged