fix(tenant configuration): explain better how to use tenants
bonitasoft/bonita-doc pull request #302
Opened 2017-05-18 15:09 UTC by educhastenier

And in particular ensure explanations are clear enough on multiple datasource
configuration when we have severals tenants.

Closes [BS-15843](https://bonitasoft.atlassian.net/browse/BS-15843)

2017-05-18 15:24 UTC, laurentleseigneur requested changes

2017-05-18 15:24 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +If you are using the Performance edition, you can create additional tenants, using the Platform API (through Java or REST).
through Java or REST API

2017-05-18 15:24 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +The _engine_ platform configuration directory is located in sub-folder: `platform_engine/`.
are you sure it's not a wildcard ?

2017-05-18 15:24 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +There is a separate _engine_ configuration directory for each tenant, located in: `current/tenants/<tenant_id>/tenant_engine`.
location is current/platform_portal/tenants/<TENANT_ID>/tenant_engine

2017-05-18 15:24 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +There is also a default tenant _engine_ configuration directory, located in: `current/tenant_template_engine`.
same comment

2017-05-18 15:24 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +A tenant can be created using the Java PlatformAPI (see the [Engine Javadoc](http://documentation.bonitasoft.com/javadoc/api/${varVersion}/index.html)) or the [platform REST API](platform-api.md).
Javadoc may be a real  http link to javadoc

2017-05-18 15:24 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +```java
👍

2017-05-18 15:24 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +The [platform REST API](platform-api.md) is a REST wrapper around the Java PlatformAPI to create the tenant.
not sure we need this, REST API call Java API, why do you introduce this unexplained "wrapper" concept ?

2017-05-18 15:24 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +    apiClient.login(TENANT_ID, "install", "install");               // here, replace TENANT_ID by the ID of the tenant you just created above
install/install doesn't sems to be the good default value since it's tenant #1 value

2017-05-18 15:24 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +    // and use the processApi...
... on new tenant

2017-05-18 15:37 UTC, educhastenier commented on md/multi-tenancy-and-tenant-configuration.md
> +There is a separate _engine_ configuration directory for each tenant, located in: `current/tenants/<tenant_id>/tenant_engine`.
nope, try again.

2017-05-18 15:38 UTC, educhastenier commented on md/multi-tenancy-and-tenant-configuration.md
> +There is also a default tenant _engine_ configuration directory, located in: `current/tenant_template_engine`.
same answer

2017-05-18 15:39 UTC, educhastenier commented on md/multi-tenancy-and-tenant-configuration.md
> +A tenant can be created using the Java PlatformAPI (see the [Engine Javadoc](http://documentation.bonitasoft.com/javadoc/api/${varVersion}/index.html)) or the [platform REST API](platform-api.md).
I don't understand

2017-05-18 15:40 UTC, educhastenier commented on md/multi-tenancy-and-tenant-configuration.md
> +The [platform REST API](platform-api.md) is a REST wrapper around the Java PlatformAPI to create the tenant.
`is a REST layer around the Java PlatformAPI...` is better?

2017-05-18 15:40 UTC, educhastenier commented on md/multi-tenancy-and-tenant-configuration.md
> +    apiClient.login(TENANT_ID, "install", "install");               // here, replace TENANT_ID by the ID of the tenant you just created above
You can have the same tenant credentials on all and every tenant.

2017-05-18 15:41 UTC, educhastenier commented on md/multi-tenancy-and-tenant-configuration.md
> +    // and use the processApi...
I'll do that.

2017-05-18 15:42 UTC, educhastenier commented on md/multi-tenancy-and-tenant-configuration.md
> +If you are using the Performance edition, you can create additional tenants, using the Platform API (through Java or REST).
ok

2017-05-18 15:42 UTC, educhastenier commented on md/multi-tenancy-and-tenant-configuration.md
> +The _engine_ platform configuration directory is located in sub-folder: `platform_engine/`.
are you talking about the trailing `slash`?

2017-05-19 07:44 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +There is a separate _engine_ configuration directory for each tenant, located in: `current/tenants/<tenant_id>/tenant_engine`.
you're right!

2017-05-19 07:47 UTC, laurentleseigneur commented on md/multi-tenancy-and-tenant-configuration.md
> +A tenant can be created using the Java PlatformAPI (see the [Engine Javadoc](http://documentation.bonitasoft.com/javadoc/api/${varVersion}/index.html)) or the [platform REST API](platform-api.md).
i meant link to platformAPI javadoc page, frame in javadoc don't help us

2017-05-29 08:12 UTC, educhastenier commented on md/multi-tenancy-and-tenant-configuration.md
> +A tenant can be created using the Java PlatformAPI (see the [Engine Javadoc](http://documentation.bonitasoft.com/javadoc/api/${varVersion}/index.html)) or the [platform REST API](platform-api.md).
Ok, I'll do that.

2017-05-29 12:28 UTC, laurentleseigneur approved these changes

2017-05-29 12:29 UTC, merged