style(release note): style improvement
bonitasoft/bonita-doc pull request #310
Opened 2017-05-30 16:08 UTC by NathalieC

fix typos
move SAML in technical update section

2017-05-30 20:15 UTC, laurentleseigneur requested changes

2017-05-30 20:15 UTC, laurentleseigneur commented on md/release-notes.md
> +Bonita BPM 7.5 includes a set of new features related to Living Application development and deployment as well as UI personalization, in addition to important technology updates and bug fixes.
remove BPM since product name has changed

2017-05-30 20:15 UTC, laurentleseigneur commented on md/release-notes.md
> +Bonita BPM Studio provides a wizard when importing a .bos that displays the duplicate artifacts (forms, connectors, ...)  and asks for user actions, between keeping the existing artifact and overwrit
remove BPM or use variable for product name

2017-05-30 20:15 UTC, laurentleseigneur commented on md/release-notes.md
> +Bonita BPM Studio provides an editor to create the Living Application descriptor (metadata and navigation) that took place in Bonita BPM Portal (Administrator profile) in previous versions. This is t
same comment

2017-05-31 07:00 UTC, NathalieC commented on md/release-notes.md
> +Bonita BPM 7.5 includes a set of new features related to Living Application development and deployment as well as UI personalization, in addition to important technology updates and bug fixes.
The product renaming will only occur from Bonita 7.6 and above.
This PR is about 7.5 release note.

2017-05-31 07:01 UTC, NathalieC commented on md/release-notes.md
> +Bonita BPM Studio provides a wizard when importing a .bos that displays the duplicate artifacts (forms, connectors, ...)  and asks for user actions, between keeping the existing artifact and overwrit
Still 7.5 and no need of a variable since 7.6 Release note will be a different page.

2017-05-31 07:01 UTC, NathalieC commented on md/release-notes.md
> +Bonita BPM Studio provides an editor to create the Living Application descriptor (metadata and navigation) that took place in Bonita BPM Portal (Administrator profile) in previous versions. This is t
Bonita BPM 7.5 is correct.

2017-05-31 07:15 UTC, laurentleseigneur approved these changes

2017-05-31 07:15 UTC, merged