fix,howto/addition-of-X-Bonita-API-Token-header-and-addition-of-an-ex…
bonitasoft/bonita-doc pull request #320
Opened 2017-06-08 14:24 UTC by jjargot

…ample-and-addition-of-a-troubleshoot-section

Addition of X-Bonita-API-Token header information
Addition of a walkthrough example
Addition of a troubleshoot

Versions: 7.4, 7.5

2017-06-08 14:31 UTC, educhastenier commented
retest this please

2017-06-08 14:40 UTC, educhastenier commented on md/rest-api-overview.md
> +The value of X-Bonita-API-Token cookie must be passed also in the header of the subsequent REST API calls, when the POST, PUR or DELTE HTTP method is used.
Typo PUT
Typo DELETE

2017-06-08 14:44 UTC, jjargot commented
I was in CC of an email with this content:

    retest this please

Nothing new appeared in the git-hub web page https://github.com/bonitasoft/bonita-doc/pull/320

The curl commands listed in the walkthroudgh have been tested once
The email was not addressed to me, my email apears to be listed in the CC
The git-hub web page does not contain any new information

So, I assumed this is not for me.

2017-06-08 14:57 UTC, jjargot commented on md/rest-api-overview.md
> +The value of X-Bonita-API-Token cookie must be passed also in the header of the subsequent REST API calls, when the POST, PUR or DELTE HTTP method is used.
thx Emmanuel
typos fixed + commit

2017-06-08 15:00 UTC, educhastenier commented
Is there a JIRA ticket to link to this PR?

2017-06-09 09:13 UTC, jjargot commented
No, there is no bug associated.
This was discovered during the implementation of the exercises for training that I had to do to be prepared to the train the trainer session for the new 7.5.0
(the changes for the 7.4 doc should be propagated to 7.5 doc)

2017-06-13 09:37 UTC, abirembaut requested changes
I have a few comments but it looks good.
However, I would rather put the "Walk-through" at the end of the page (after the general explanation on the different methods since we use them in the walk-through...). It can still me mentioned here, though (e.g. : see walk-through at the bottom of the page)

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +The response to this call generates cookies, which must be transfered with each subsequent calls. If the Web REST is being used in an application running in a web browser, this is handled automatical
I know it was not introduced by your PR, but could you change "If the Web REST is being used in an application" into "If the REST API is used by an application"

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +`curl` is available on Linux OS and it transfers data from or to a server with various protocols such as HTTP and HTTPS, see manual page.
if we say "see manual page" we should put a link to it or give the command to execute, but i don't think this is necessary.
We can just finish the sentence with "HTTP and HTTPS."

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +Create a new `Registration` process
rather: "Create a new process named \`Registration\`"

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +#### Start a 7.4.0+ Studio
a line break before this title would improve readability

I would rename the title in "Deploy a process"
and then the first point would be : "- Start a process" (no need for the version as we are in the 7.4 doc and this will be automatically merged in subsequent versions)

e.g. :

\#\#\# Deploy a process
\- Start a studio
\- Make sure the current organization contains a User with name \`walter.bates\` and password \`bpm\`
\- Create a new process named \`Registration\`
\- Configure the process so that Walter Bates will be able to start it
\- Click on the Run button

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +#### Install `curl` command line tool
a line break before this title would improve readability

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +#### Login
a line break before this title would improve readability

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +#### List installed process definitions
a line break before this title would improve readability

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +    ]
I don't know if this is a god idea to show 2 processes when we only talked about deploying one. This can be confusing. Maybe we should show a response with only the registration process

the json response could be in a code block

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +#### Instantiate one case of the `Registration` process
a line break before this title would improve readability

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +The response shows that there are 2 process definitions installed.
"one process definition installed." (if we change the json response to only keep on process)

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +#### Logout
a line break before this title would improve readability

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +#### Troubleshooting
a line break before this title would improve readability

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +The response's HTTP status code is `401 Unauthorized`:
"If the HTTP response status code is"

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> + - check that the cookies had been transfered with the call
I would rather say:
"check **if** the cookies **have** been transfered with the call"
or
"**make sure** that the cookies **have** been transfered with the call"

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> + - check that the cookies transfered with the call are the ones generated during the last sucessfull login call
same comment as above

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> + - if one of the PUT, DELETE or POST method is used, check that the X-Bonita-API-Token header is included
same comment as above

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> + - if the X-Bonita-API-Token header is included, check that the value is the same that the cookie generated during the last login
same comment as above
and
"the value is the same as the one of the cookie..."

2017-06-13 09:37 UTC, abirembaut commented on md/rest-api-overview.md
> +### Walk-through: Example shows how to instantiate one case using the REST API
Walk-through: How to start a case uning the REST API
(anyway, "Example shows" can be removed)

2017-06-13 10:20 UTC, jjargot commented on md/rest-api-overview.md
> +The response to this call generates cookies, which must be transfered with each subsequent calls. If the Web REST is being used in an application running in a web browser, this is handled automatical
section moved to the end
sentence updated

2017-06-13 10:20 UTC, jjargot commented on md/rest-api-overview.md
> +### Walk-through: Example shows how to instantiate one case using the REST API
done

2017-06-13 10:24 UTC, jjargot commented on md/rest-api-overview.md
> +#### Install `curl` command line tool
do not understand where to put it

2017-06-13 10:25 UTC, jjargot commented on md/rest-api-overview.md
> +`curl` is available on Linux OS and it transfers data from or to a server with various protocols such as HTTP and HTTPS, see manual page.
done

2017-06-13 10:29 UTC, jjargot commented on md/rest-api-overview.md
> +#### Start a 7.4.0+ Studio
ok, line break inserted => there is no change in preview
done

2017-06-13 10:29 UTC, jjargot commented on md/rest-api-overview.md
> +Create a new `Registration` process
ok

2017-06-13 10:30 UTC, jjargot commented on md/rest-api-overview.md
> +#### Login
ok

2017-06-13 10:30 UTC, jjargot commented on md/rest-api-overview.md
> +#### List installed process definitions
done

2017-06-13 11:51 UTC, jjargot commented on md/rest-api-overview.md
> +    ]
second useless process removed
json is already in a code block

2017-06-13 11:52 UTC, jjargot commented on md/rest-api-overview.md
> +#### Logout
done

2017-06-13 11:52 UTC, jjargot commented on md/rest-api-overview.md
> +#### Instantiate one case of the `Registration` process
done

2017-06-13 11:53 UTC, jjargot commented on md/rest-api-overview.md
> +The response shows that there are 2 process definitions installed.
done

2017-06-13 11:53 UTC, jjargot commented on md/rest-api-overview.md
> +#### Troubleshooting
done

2017-06-13 11:55 UTC, jjargot commented on md/rest-api-overview.md
> + - check that the cookies had been transfered with the call
done

2017-06-13 11:55 UTC, jjargot commented on md/rest-api-overview.md
> + - check that the cookies transfered with the call are the ones generated during the last sucessfull login call
done

2017-06-13 11:56 UTC, jjargot commented on md/rest-api-overview.md
> + - if one of the PUT, DELETE or POST method is used, check that the X-Bonita-API-Token header is included
done

2017-06-13 11:57 UTC, jjargot commented on md/rest-api-overview.md
> + - if the X-Bonita-API-Token header is included, check that the value is the same that the cookie generated during the last login
done

2017-06-13 12:04 UTC, abirembaut commented on md/rest-api-overview.md
> +    ]
Yes, indeed ! my bad

2017-06-13 12:06 UTC, abirembaut approved these changes

2017-06-13 12:06 UTC, abirembaut commented
:+1:

2017-06-13 12:12 UTC, merged