feat(profile) profile in studio doc update
bonitasoft/bonita-doc pull request #337
Opened 2017-07-04 12:45 UTC by alachambre

* creation of the page _profileCreation.md_ to document the profile editor
* perform some refactoring regarding the old documentation, to highlight the new feature and the use of the studio as development platform. 

closes [BS-16816](https://bonitasoft.atlassian.net/browse/BS-16816)

2017-07-04 12:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=337) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=337) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-doc?pullRequest=337) it.</sub>

2017-08-11 10:46 UTC, NathalieC requested changes

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +Basically, a **profile** is an XML file. It contains the profile name, the mapping with the organization (which users / groups / roles / memberships have this profile) and the portal menu entries (me
it contains a description too

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +Basically, a **profile** is an XML file. It contains the profile name, the mapping with the organization (which users / groups / roles / memberships have this profile) and the portal menu entries (me
When it's the first reference in a page, we need to use "Bonita Portal", and then "the portal" is ok.

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +Before Bonita 7.6, this portal tab was the only way to create and manage profiles.
Since Bonita 7.6.0, Bonita Studio offers this feature, for better packaging and deployment.

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +An **file of profiles** is an XML file containing one or more profiles.
A *file of profiles*

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +
Files of profiles are also handy to be used in different environments: you can create different files, with the same profiles, but each profile is mapped to different entities of the organization depending on the target environment.
Therefore, you could have a "profiles_dev.xml", a "profiles_UAT.xml", and a "profiles_prof.xml" files of profiles.

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +This file can only contain default profiles and cannot be renamed or deleted.
Only the mapping between default profiles and entities of the organization can be edited.

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +From Bonita Studio, click on **Organization** -> **Profile** -> **New...**
This should be "Profiles", even in the product, like "Connectors".
"REST API extensions" should also be made plural, like "Application descriptors" in the Development menu.

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +In the mapping section you can map Users / groups / roles / memberships to your profile. You have to map your profile with elements of the active organization.
either "Users / Groups / Roles / Memberships" or no upper case at all.

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +⚠  Nodes in the group tree are **independent** ⚠  It means that mapping `/acme` to your profile won't map `/acme/hr` to it. Each node has to be mapped individually to be took into account.
"taken into account"

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +Pages proposed are those provided by default in the Bonita Portal and those created with the UI designer. You can reference a custom page only present in the portal, but you will have to write its ex
"in Bonita Portal". (no "the")
UI Designer (capital "D")
"...a custom page only if it is imported to the portal, and you will..."

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +To map a new application to this profile, you have to open the application and then chose this profile in the profile section of the [application descriptor editor](applicationCreation.md)
"choose"
"**Profile** field"

2017-08-11 10:46 UTC, NathalieC commented on md/profileCreation.md
> +⚠  Nodes in the group tree are **independent** ⚠  It means that mapping `/acme` to your profile won't map `/acme/hr` to it. Each node has to be mapped individually to be took into account.
You need to promote the "Add subtree" feature here, how it helps in dev, and how it behaves differently in prod

2017-08-17 07:52 UTC, alachambre commented on md/profileCreation.md
> +⚠  Nodes in the group tree are **independent** ⚠  It means that mapping `/acme` to your profile won't map `/acme/hr` to it. Each node has to be mapped individually to be took into account.
what's the difference? The mapping doesn't change, it's just that you don't have the tool in prod, but we are talking about the studio feature here no?

2017-08-31 11:25 UTC, merged