feat(Migration) layout Migration step to 7.6.0
bonitasoft/bonita-doc pull request #346
Opened 2017-07-18 14:30 UTC by julienmege

How to migrate layout, to navigate between pages without reloading the entire page.

Covers[BS-16855](https://bonitasoft.atlassian.net/browse/BS-16855)

2017-07-19 11:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=346) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=346) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: julienmege<br/>:x: NathalieC<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-doc?pullRequest=346) it.</sub>

2017-07-19 11:53 UTC, NathalieC commented on md/customize-living-application-layout.md
>  :::
So what's the option if we want to avoid the bug and still customize the layout?
It seems that it's either/or but not both.

2017-07-26 14:22 UTC, abirembaut requested changes
Just 2 small comments
Also, maybe we should explain that the new layout leverage an HTML5 feature (pushState)

2017-07-26 14:22 UTC, abirembaut commented on md/customize-living-application-layout.md
> +Since Bonita BPM 7.3, we have made some changes in the default layout. You will have to remove `layout.css` from the page asset to make the following instructions relevant.
from the page asset**s**

2017-07-26 14:22 UTC, abirembaut commented on md/customize-living-application-layout.md
> +8. On Bonita Portal server, edit the layout and import the newly exported layout
missing a step before that: export the updated layout

2017-07-31 12:54 UTC, abirembaut requested changes
still a few comments. Other than that, it lloks good to me

2017-07-31 12:54 UTC, abirembaut commented on md/customize-living-application-layout.md
> +You will need to install Git, then clone the repository "https://github.com/bonitasoft/bonita-distrib.git".
If you don't already have Git(link to git-scm.com), you will need to install it, then clone...

2017-07-31 12:54 UTC, abirembaut commented on md/customize-living-application-layout.md
> +9. On Bonita Portal, edit the layout and import the newly exported layout
In Bonita portal

2017-07-31 12:54 UTC, abirembaut commented on md/customize-living-application-layout.md
> +If you want to import a custom layout created with a UI Designer older than version 7.3.0 into an application working with Bonita 7.3.0 or greater, you have to perform the following steps to prevent
...to prevent the issue from occurring :

2017-07-31 12:54 UTC, abirembaut commented on md/customize-living-application-layout.md
> +5. Select the iFrame widget and set the **reziseToContent** option to _yes_ (this option has been removed in 7.6.0, as the iframe is now resize using CSS)
resize**d**

2017-07-31 12:54 UTC, abirembaut commented on md/release-notes.md
> +  See how to [update your custom layout](customize-living-application-layout.md#improve-navigation) to take benefit of this improvement.
either "to take advantage of" or "to benefit from"

2017-07-31 12:54 UTC, abirembaut commented on md/customize-living-application-layout.md
> +Starting with Bonita 7.6.0, when the user clicks on any menu item, only the content of the iframe with the targeted page is refreshed: it does not reload the entire page anymore.
I would mention : "The HTML5 History API is used to achieve that."

2017-07-31 14:36 UTC, abirembaut commented
LGTM

2017-07-31 14:36 UTC, merged