fix(database): encoding and collation fix for PostgreSQL and SQL Server
bonitasoft/bonita-doc pull request #347
Opened 2017-07-18 16:23 UTC by amottier

Current documentation requires to do something impossible:
- Configure SQL Server for UTF-8 (generic instruction for all database vendors)
- Configure PostgreSQL to be case insensitive (generic instruction for all database vendors). This is actually implemented by https://github.com/bonitasoft/bonita-engine/blob/master/services/bonita-persistence/bonita-persistence-hibernate/src/main/java/org/bonitasoft/engine/persistence/PostgresInterceptor.java

Close BS-16880

2017-07-18 16:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=347) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=347) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-doc?pullRequest=347) it.</sub>

2017-07-19 09:54 UTC, tbouffard requested changes
When I talk about collations with @amottier, choosing AI instead of AS has been a subject of attention.
So for all db vendors, I would insist on why we suggest to use AI.

2017-10-16 13:08 UTC, educhastenier commented
Why do you have to precise it if it is already the default Bonita behaviour in PostgresInterceptor.java ?

2017-11-29 14:01 UTC, tbouffard commented
As seen with @amottier I am closing this PR as he currently has no time to work on it.
It will be reopened later.

Please do not delete the related branch to not loose the existing work.

2017-11-29 14:01 UTC, closed without merging