add(Install, HW and SW Reqts): add instructions to patch Chrome 60
bonitasoft/bonita-doc pull request #370
Opened 2017-08-25 14:30 UTC by ugaston

Versions: Proposal for 7.5 (should be adapted for all versions starting from 6.2)

Set of instructions to patch Bonita BPM Platform for Chrome 60+ versions, both for Subscription and Community users.

_Reference bug: **BS-16954**- Portal incompatible with Chrome 60 (released 25 Jul 2017)
Escalation reference: **2017-07-31 - University of Queensland - Risk Action Plan** (https://bonitasoft.atlassian.net/wiki/spaces/0015700001oVd76/pages/127393923/2017-07-31+-+University+of+Queensland+-+Risk+action+plan+-+Chrome+60#space-menu-link-content)_

2017-08-25 14:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=370) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=370) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-doc?pullRequest=370) it.</sub>

2017-08-29 10:55 UTC, tbouffard commented
@ugaston can you please sign the CLA?

2017-08-29 10:56 UTC, tbouffard commented
@ugaston does this modification should also be applied to doc 7.3 and 7.4? I have just seen you created the pull request on the 7.5 branch.

2017-08-29 11:59 UTC, ugaston commented
Basically, the procedure to patch the portal has to be documented for all versions starting from 6.2.

This is (version-specific details notwithstanding) the procedure to communicate, but the Hardware and Software Requirements page has evolved slightly over the versions, so the actual placement of the procedure may need adapting for the previous versions.

2017-09-06 15:49 UTC, abirembaut requested changes
LGTM
Just one small comment

2017-09-06 15:49 UTC, abirembaut commented on md/hardware-and-software-requirements.md
> +   ```java
should be javascript

2017-09-07 07:18 UTC, ugaston commented
Thank you for your comment, Anthony. Good catch.
I have now replaced "java" with "javascript", as suggested.

2017-09-07 07:45 UTC, laurentleseigneur commented on md/hardware-and-software-requirements.md
> +   ```xml
this script block is `javascript`, not `xml`

2017-09-07 07:55 UTC, sperfect commented on md/hardware-and-software-requirements.md
> +      // This patch fixes xhr.getAllResponseHeaders unwanted behavior whithin Bonita Portal context
within

2017-09-07 08:09 UTC, ugaston commented
Thank you, Laurent and sperfect (?) for your comments.
My last commit should have taken good care of those.

2017-09-07 12:19 UTC, abirembaut approved these changes

2017-10-17 09:54 UTC, abirembaut commented
LGTM

2017-10-17 09:54 UTC, merged