feat(doc): improve cache policy documentation
bonitasoft/bonita-doc pull request #377
Opened 2017-09-04 09:20 UTC by benjaminParisel

2017-09-04 09:47 UTC, benjaminParisel commented
retest this please

2017-09-04 09:55 UTC, benjaminParisel commented
restest this please

2017-09-04 10:06 UTC, educhastenier commented
retest this please

2017-09-05 08:13 UTC, educhastenier requested changes

2017-09-05 08:13 UTC, educhastenier commented on md/cache-configuration-and-policy.md
> +<a id="portal_and_mobile">
Remove this change with single `/>` at the end

2017-09-15 08:03 UTC, educhastenier commented
retest this please

2017-09-15 08:03 UTC, educhastenier approved these changes

2017-09-15 08:14 UTC, educhastenier commented
Navigation works!

2017-09-15 08:14 UTC, merged