tr(groovy scripts): document the new security Groovy scripts mechanism
bonitasoft/bonita-doc pull request #392
Opened 2017-10-12 15:44 UTC by educhastenier

Strongly encourage the use of default package

Closes [BS-17237](https://bonitasoft.atlassian.net/browse/BS-17237)

2017-10-13 15:16 UTC, laurentleseigneur requested changes

2017-10-13 15:16 UTC, laurentleseigneur commented on md/rest-api-authorization.md
> +* add the script to the `setup/platform_conf/current/tenant_template_security_scripts` folder
for first run, it should be the `initial` folder

2017-10-13 15:43 UTC, abirembaut reviewed
LGTM
Just a small comment

2017-10-13 15:43 UTC, abirembaut commented on md/rest-api-authorization.md
> +* make sure this .groovy file is placed in the default directory, under 'initial/tenant_template_security_scripts/' or under 'current/tenants/TENANT_ID/tenant_security_scripts/'
I would just add "if the platform has already been started" at the end of this sentence

2017-10-16 12:11 UTC, educhastenier commented on md/rest-api-authorization.md
> +* add the script to the `setup/platform_conf/current/tenant_template_security_scripts` folder
nice catch

2017-10-16 13:44 UTC, laurentleseigneur approved these changes

2017-10-16 13:44 UTC, merged