fix(ReleaseNote): add a note about the new API method
bonitasoft/bonita-doc pull request #500
Opened 2018-03-26 12:42 UTC by danila-m

addProcessComment behavior changed (some time ago in fact).
New method addProcessCommentOnBehalfOfUser() to replicate old behavior added.

Relates to : [BS-18208](https://bonitasoft.atlassian.net/browse/BS-18208)

2018-03-27 06:01 UTC, NathalieC commented on md/release-notes.md
> +What it means in practice: if you are calling the method outside of groovy scripts, you can use the method you like ( addProcessComment() being probably more practical), and your process will not req
What it means in practice if your process has been designed prior to Bonita 7.3:  
- If you are calling the method outside of groovy scripts, you can use the method you like ( addProcessComment() being probably more practical), and your process will not require any additional modification. 
- If you are calling the method from a groovy script and want to maintain the previous behavior, you will have to modify your groovy scripts to use the new API method.
- If your process has been designed in Bonita 7.4, 7.5 or 7.6, ...

2018-03-27 06:02 UTC, NathalieC commented on md/release-notes.md
> +* [addProcessComment()](https://documentation.bonitasoft.com/javadoc/api/7.7/org/bonitasoft/engine/api/ProcessRuntimeAPI.html#addProcessComment-long-java.lang.String-) method in ProcessRuntimeAPI has
"some releases ago" : "in Bonita 7.3", so we better understand why you mention 7.3 later on in the "what in means in practical" paragraph.

2018-03-30 08:35 UTC, nchabanoles requested changes

2018-03-30 08:35 UTC, nchabanoles commented on md/release-notes.md
> +* [addProcessComment()](https://documentation.bonitasoft.com/javadoc/api/7.7/org/bonitasoft/engine/api/ProcessRuntimeAPI.html#addProcessComment-long-java.lang.String-) method in ProcessRuntimeAPI has
What changed is the fix of this bug: https://bonitasoft.atlassian.net/browse/BS-14276

Operations on human tasks are asynchronous (as it should have been from 7.0.0). Hence all methods relying of Session to get the userID will find -1 as a value.

All scripts that want to perform an action on behalf of the user executing the task, should rely on the task assignee to do so. (There is no user logged hence the -1 value in the sessions; as the execution is asynchronous).

With the new API method, the script can leave a comment on behalf of the user. Note: this use case has never been considered before. As a comment was thought to be left by the user himself / herself.

2018-03-30 15:49 UTC, merged