fix(escape character) Remove escape character if used into quote ``
bonitasoft/bonita-doc pull request #510
Opened 2018-04-09 12:22 UTC by julienmege

closes(BS-17994)[https://bonitasoft.atlassian.net/browse/BS-17994]

2018-04-11 08:39 UTC, NathalieC commented
retest this please

2018-04-11 08:52 UTC, tnguyen1 commented
retest this please

2018-04-11 09:05 UTC, NathalieC commented
Some "\" remain in bpm-api.md.
Could you remove them?

2018-06-08 08:35 UTC, educhastenier commented on md/bpm-api.md
> +  * `user_id=:userId}`: retrieve only the actorMembers related to the specified user\_id. `/API/bpm/actorMember?p=0&c=10&f=actor_id%3d1&f=user_id%3d101`
extra `}` character

2018-06-08 08:42 UTC, educhastenier requested changes
There are still places where ``` character is still visible in the final rendering, on pages http://doc.rd.lan:50510/bonita/7.3/identity-api
http://doc.rd.lan:50510/bonita/7.3/bpm-api

Please fix them

2018-06-08 12:10 UTC, tbouffard approved these changes
Latest commits from @julienmege seems fixing the remarks noticed by @educhastenier

2018-06-08 12:28 UTC, merged