Feat(ldap synchronizer custominfo)
bonitasoft/bonita-doc pull request #513
Opened 2018-04-12 21:24 UTC by pierre-yves-monnet

Documentation for the new LDAP Synchronizer attributes to synchronize custom information

2018-04-12 21:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=513) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-doc?pullRequest=513) before we can accept your contribution.<br/>**10** out of **12** committers have signed the CLA.<br/><br/>:white_check_mark: jjargot<br/>:white_check_mark: dtranquang<br/>:white_check_mark: educhastenier<br/>:white_check_mark: tbouffard<br/>:white_check_mark: julienmege<br/>:white_check_mark: benjaminParisel<br/>:white_check_mark: laurentleseigneur<br/>:white_check_mark: rbioteau<br/>:white_check_mark: alachambre<br/>:white_check_mark: danila-m<br/>:x: bonita-ci<br/>:x: pierre-yves-monnet<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-doc?pullRequest=513) it.</sub>

2018-04-13 07:33 UTC, rbioteau commented
please make the pr on 7.7 branch

2018-04-13 07:41 UTC, educhastenier commented
no need to close the PR, just change the base branch at the top of the page

2018-04-13 15:39 UTC, tbouffard commented
@pierre-yves-monnet please sign the CLA to let us merge this PR
Thanks

2018-04-17 14:09 UTC, rbioteau requested changes

2018-04-17 14:09 UTC, rbioteau commented on md/ldap-synchronizer.md
>  Set the API access mode used by the LDAP Synchronizer, by editing the `<LDAP_SYNCHRONIZER>\BonitaSubscription-7.3.x-LDAP-Synchronizer.(bat or sh)` file.
change `7.3.x` with `<version>`

2018-04-17 14:09 UTC, rbioteau commented on md/ldap-synchronizer.md
> +**Note**: to use a special character in a properties file, use the Unicode equivalent. For example, for Ã  use \\u00E0\.
`à` not `Ã`

2018-04-17 14:09 UTC, rbioteau commented on md/ldap-synchronizer.md
> +Example: if you set the format to "?yyyy-mm"Â�, you will get one new log file per month.
remove `Â�`

2018-04-17 14:09 UTC, rbioteau commented on md/ldap-synchronizer.md
> +A 'Custom Information' not declared in mapper.properties will not be modified. When the Ldap Object doesn't have an property, it will not be modified.
a property

2018-04-17 14:09 UTC, rbioteau commented on md/ldap-synchronizer.md
> +Same as partial, plus if the Ldap Object doesn't have an property, it will be set to null
a property

2018-04-18 07:06 UTC, rbioteau approved these changes

2018-04-18 07:06 UTC, merged