doc(BDM AC): add the make several app options
bonitasoft/bonita-doc pull request #539
Opened 2018-05-31 17:14 UTC by NathalieC

* when considering the fact that several profiles can access an attribute or not, add the option of creating one app per profile, with a different page: one with the field, and one without. Play with the property hidden is not always the right choice.

2018-06-01 09:36 UTC, alachambre requested changes

2018-06-01 09:36 UTC, alachambre commented on md/bdm-access-control.md
> +_medicalComment_ will not be accessible to the HR trainees.
2 spaces at the end, else the return line won't be done..

2018-06-01 09:36 UTC, alachambre commented on md/bdm-access-control.md
> +To manage this and other differences between what profiles can access, you hove two options:
type: you have

2018-07-23 12:47 UTC, NathalieC commented
@alachambre ; can you please review again?

2018-07-23 12:54 UTC, alachambre commented
It's correct, but what a strange idea...
In which world is it better to have several pages with almost the same content just for a small difference when you can manage it in the same page??? It means that you will have the maintain the two pages, report all major changes twice ect ... 
Certainly not a good option in my view, but yes you can do that if you want to.

2018-07-30 16:14 UTC, merged