feat(git) migrate a svn repository to git
bonitasoft/bonita-doc pull request #596
Opened 2018-10-04 16:05 UTC by rbioteau

Closes BS-18789

2018-10-26 14:16 UTC, alachambre reviewed
Looks good, it could be interesting to test it with a svn repo with a real historic?

2018-11-23 16:44 UTC, tbouffard commented
I am currently testing it with our internal svn repo

2018-11-26 12:13 UTC, tbouffard requested changes
In addition to my comments, I have noticed that
* there is no information about renaming trunk and branches, transforming svn tags into git tags
* to perform the branch operation, having a bar repo is usefull as described in the linked resources

let's talk about it in person

2018-11-26 12:13 UTC, tbouffard commented on md/migrate-a-svn-repository-to-github.md
> +Then run the following command to retrieve the svn committers:
```suggestion
Then run the following command from the locally checkouted repository to retrieve the svn committers:  
```

2018-11-26 12:13 UTC, tbouffard commented on md/migrate-a-svn-repository-to-github.md
> +
ℹ️ add the following
Copy the `authors-transform.txt` to a directory
From this repository run:

2018-11-26 12:13 UTC, tbouffard commented on md/migrate-a-svn-repository-to-github.md
> +
ℹ️ the svn url must point to the root of the bonita repository (including trunk, tags, branches) to make the git svn clone work.
I suggest to add this information because my 1st attempt failed because of I was only cloning from the trunk

2018-11-26 12:13 UTC, tbouffard commented on md/migrate-a-svn-repository-to-github.md
> +Add a .gitignore in `~/temp` with the following content
⚠️ as discussed together, we should mention that the svn ignore should not be migrated
This is because new files/folders must be ignored when using git

2018-11-26 12:13 UTC, tbouffard commented on md/migrate-a-svn-repository-to-github.md
> +* git: ```sudo apt-get install git```
```suggestion
* git: ```sudo apt-get install git``` (tested with git 2.17.1)
```

2018-12-12 10:51 UTC, merged