doc(rest api): Update REST API extension documentation to cover Community Edition
bonitasoft/bonita-doc pull request #619
Opened 2018-11-08 15:17 UTC by amottier

Add information about creation of REST API extension using Community Edition.

Closes BS-17850

Insert your Pull Request description here...

* add support for ...
* fix ... behaviour
* refactor ....

2018-11-23 09:37 UTC, tbouffard requested changes
Good job, very clear.
Minor changes requested and suggested

2018-11-23 09:37 UTC, tbouffard commented on md/rest-api-extensions.md
> +        return buildPagedResponse(responseBuilder, new JsonBuilder(result).toPrettyString(), startIndex, endIndex, context.apiClient.identityAPI.numberOfUsers)
```suggestion
        return buildPagedResponse(responseBuilder, new JsonBuilder(result).toString(), startIndex, endIndex, context.apiClient.identityAPI.numberOfUsers)
```

2018-11-23 09:37 UTC, tbouffard commented on md/rest-api-extensions.md
> +        return buildPagedResponse(responseBuilder, new JsonBuilder(result).toPrettyString(), startIndex, endIndex, context.apiClient.identityAPI.numberOfUsers)
ℹ️ This is to reduce the response size and the same should be applied for the other example (see line 248)

2018-11-23 09:37 UTC, tbouffard commented on md/rest-api-extensions.md
> +The following sections show how to create a REST API extension. As an example, we create a REST API extension that use Bonita BPM Engine to provide user information (first name, last name, email addr
:warning typos

2018-11-23 09:37 UTC, tbouffard commented on md/rest-api-extensions.md
> +The following sections show how to create a REST API extension. As an example, we create a REST API extension that use Bonita BPM Engine to provide user information (first name, last name, email addr
```suggestion
The following sections show how to create a REST API extension. As an example, we create a REST API extension that uses the Bonita BPM Engine to provide user information (first name, last name, email address).
```

2018-11-23 09:37 UTC, tbouffard commented on md/rest-api-extensions.md
> +* One Groovy script files per API extension. The Groovy script files define the business logic of the API extensions.
⚠️ typo

2018-11-23 09:37 UTC, tbouffard commented on md/rest-api-extensions.md
> +* One Groovy script files per API extension. The Groovy script files define the business logic of the API extensions.
```suggestion
* One Groovy script file per API extension. The Groovy script files define the business logic of the API extensions.
```

2018-12-03 16:42 UTC, amottier commented
@tbouffard I amend my commit with your recommendation. If everything is ok can you do a quick final review and merge? Thanks.

2018-12-06 09:44 UTC, tbouffard commented
LGTM, for the next time, could you avoid force-pushing, this makes the review harder.
We can squash commit while merging the PR 😸

2018-12-06 09:45 UTC, tbouffard approved these changes

2018-12-06 09:45 UTC, merged