fix(web service) connector web service exemple v2
bonitasoft/bonita-doc pull request #642
Opened 2018-12-17 16:59 UTC by alachambre

* v2 of the connector web service exemple, the previous exemple was using v6 forms and a dead web service. 

closes [BS-18490](https://bonitasoft.atlassian.net/browse/BS-18490)

2018-12-19 13:32 UTC, danila-m commented
7.4 is not supported anymore, this needs to be merged in 7.5

2018-12-21 15:13 UTC, PierrickVoulet requested changes

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +1. In the BDM, create a business object with the following attributes:
Specify the name of the BO: "Country" based on following paragraphs

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +![web service process diagram](images/connector_webservice_tuto/webservice_diagram.png)
Better to go from an implicit to an explicit gateway

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +![web service process diagram](images/connector_webservice_tuto/webservice_diagram.png)
Add a name to the gateway like "is this country Capital already known?" and replace the condition names to "yes" and "no" instead

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +![web service process diagram](images/connector_webservice_tuto/webservice_diagram.png)
Do not use a technical name in display name (separate words for example). This applies to anything that is displayed in the diagram: pool, lane, condition, task, gateway, etc.

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +![web service process diagram](images/connector_webservice_tuto/webservice_diagram.png)
Rename "Start1" to "Start" and "End1" to "End"

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +![web service process diagram](images/connector_webservice_tuto/webservice_diagram.png)
This is the version I did on my side: 
![image](https://user-images.githubusercontent.com/6769971/50347356-46a88200-0503-11e9-82b8-502b53cbee7a.png)

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +5. Add an instantiation form: select the Pool \> Execution, click on the _**Instantiation form tab**_, and click on the pencil on the right of the field _Target form_, it should open the UI designer.
Remove the existing country input widget (automatically generated)

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +    - **Availables values:** countries
click on Fx and select the variable "countries"

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +  -  Ensure in the preview that the combo box gives the possibility to select one of the countries, and we are done for the instantiation form.
Click on "Preview" to make sure that....

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +7. Select the  _**countryUnknown**_ flow,  go on the _**General tab**_ and set this flow as the Default flow.
The "no" flow

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +8.  Select the  _**countryAlreadyKnown**_ flow, go on the _**General tab**_. Check _Use expression_, and add the following script as the expression to use:
The "yes" flow

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +9. Select the _**retrieveAlreadyKnownCapital task**_, go on the _**Execution tab**_ and click on _**Operations**_. Add the following operation:
Select the "Retrieve Already Known Capital"

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +  - **Operation**: takeValueOf
"Takes value of"

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +10. Select the _**retrieveUnknownCapital**_ task, go on the _**Execution tab**_ and click on _**Connectors in**_.
"Retrieve Unknown Capital"

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +* **Operation**: Java method -> setCapital
"Use a Java method"

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +       <?xml version="1.0" encoding="utf-8"?>
Indentation is not right

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +16. Select the _**retrieveUnknownCapital**_ task, go on the _**Execution tab**_, click on _**Operations**_ and add the following operation:
"Retrieve Unknown Capital"

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +* **Operation**: Java method -> setId
"Use a Java method"

2018-12-21 15:13 UTC, PierrickVoulet commented on md/web-service-tutorial.md
> +17. Select the _**DisplayCapital**_ task, go on the _**Execution tab**_, click on _**Form**_ and click on the pencil to create the form of this task. The UI Designer should open. The idea here is to
"Display Capital"

2018-12-21 15:13 UTC, PierrickVouletBonitasoft commented on md/web-service-tutorial.md
> +17. Select the _**DisplayCapital**_ task, go on the _**Execution tab**_, click on _**Form**_ and click on the pencil to create the form of this task. The UI Designer should open. The idea here is to
Missing step to rename the form to "displayCapital"

2018-12-21 15:13 UTC, PierrickVouletBonitasoft commented on md/web-service-tutorial.md
> +* Insert a text widget in the form, with the following content:
"Text property" instead of "content"

2018-12-21 15:13 UTC, PierrickVouletBonitasoft commented on md/web-service-tutorial.md
> +Save the form, and we are done.
This is not blocking but the overview form has not been set for the pool so there is a warning on the diagram.

2018-12-21 15:13 UTC, PierrickVouletBonitasoft commented on md/web-service-tutorial.md
> +You can test the process on the portal, you have to select a country to instantiate the case, and then the capital of this country is displayed on the next human case. The web service is used to retr
Detail the steps

- Select the pool
- Configure the actor mapping to the group "/acme"
- Click on the "Run" button to install and enable the process and be redirected to the instantiation form
- From the instantiation form in your browser, select a country and submit
- The browser will be redirected to the user perspective in the Portal
- A new task "Display Capital" should be available (refresh if not), click on it
- The capital should appear on its associated form

2019-01-16 14:00 UTC, educhastenier commented
retest this please

2019-01-17 16:22 UTC, alachambre commented
OK to merge?

2019-01-17 16:31 UTC, PierrickVoulet approved these changes

2019-01-17 16:34 UTC, merged