<!--  Insert your contribution description here. Ensure your contribution fills the Contributing Guidelines described here: https://github.com/bonitasoft/bonita-doc/blob/7.3/CONTRIBUTING.md  -->
bonitasoft/bonita-doc pull request #691
Opened 2019-03-12 10:13 UTC by baptistemesta

Insert your Pull Request description here...

* add support for ...
* fix ... behaviour
* refactor ....

2019-03-12 14:44 UTC, educhastenier commented on md/release-notes.md
> +### Asynchronous connetor execution
typo

2019-03-12 14:45 UTC, educhastenier commented on md/connectors-execution.md
> +Connectors are extension point that can be added to a process to extend Bonita Runtime capabilities. They are a piece of code having inputs defined as `Expressions` and outputs that are defined as `O
```suggestion
Connectors are extension points that can be added to a process to extend Bonita Runtime capabilities. They are a piece of code having inputs defined as `Expressions` and outputs defined as `Operations`.
```

2019-03-12 14:45 UTC, educhastenier commented on md/connectors-execution.md
> +## Executiion mechanism
```suggestion
## Execution mechanism
```

2019-03-12 14:46 UTC, educhastenier commented on md/release-notes.md
> +Connectors are executed in an asynchrous manner. in earlier version each work was waiting for the connector to end before processing other workload resulting in degraded performances if few connector
```suggestion
Connectors are executed in an asynchrous manner. In earlier versions each work was waiting for the connector to end before processing other workload. This resulted in degraded performance if few connectors had a long execution time.
```

2019-03-12 14:47 UTC, educhastenier commented on md/release-notes.md
> +Worker thread are now releases as soon as the execution of the connector is triggered. see [connector execution page](connectors-execution.md) for more details.
```suggestion
Worker threads are now released as soon as the execution of the connector is triggered. see [connector execution page](connectors-execution.md) for more details.
```

2019-03-12 14:47 UTC, educhastenier requested changes
a few formatting remarks

2019-03-13 09:30 UTC, baptistemesta commented
thanks for fixing my messy english :)

2019-03-14 09:02 UTC, educhastenier approved these changes

2019-03-20 13:28 UTC, merged