RN(migration tool): (late) update changelog page
bonitasoft/bonita-doc pull request #764
Opened 2019-06-07 10:16 UTC by educhastenier

2019-06-07 13:13 UTC, educhastenier commented
I removed the pre-7.6.0 versions, as they are not supported anymore.
:question: I hope it's ok for you...

2019-06-07 15:03 UTC, tbouffard requested changes

2019-06-07 15:03 UTC, tbouffard commented on md/migration-tool.md
> +## 2.40.3 - May. 27th, 2019 ??
```suggestion
## 2.40.3 - May. 27th, 2019 (Bonita 7.8.4)
```

2019-06-07 15:03 UTC, tbouffard commented on md/migration-tool.md
> +## 2.40.2 - May. 23rd, 2019 ??
```suggestion
## 2.40.2 - May. 23rd, 2019 (Bonita 7.8.4)
```

2019-06-07 15:03 UTC, tbouffard commented on md/migration-tool.md
> +## 2.40.1 - April. xxth, 2019 ??
```suggestion
## 2.40.1 - May. 17th, 2019 (Bonita 7.8.4)
```

2019-06-11 11:24 UTC, tbouffard approved these changes

2019-06-11 11:24 UTC, merged