feat(migration): Add the release note for migration tool 2.43.0
bonitasoft/bonita-doc pull request #794
Opened 2019-07-26 14:13 UTC by danila-m

2019-07-29 09:51 UTC, pabloalonso requested changes

2019-07-29 09:51 UTC, pabloalonso commented on md/migration-tool.md
> +* BS-19371 Migration to 7.7.0 (sometimes) fails on oracle with migration tool 2.42.0.
```suggestion
* BS-19371 Migration to 7.7.0 (sometimes) fails when recreating arch_contract_data PK on oracle with migration tool 2.42.0.
```

2019-07-29 13:19 UTC, educhastenier approved these changes
Looks good to me :+1:

2019-07-30 07:24 UTC, NathalieC commented
Yesterday, at the demo, you said that a specific behavior has been implemented in the previous migration tool (back up-ing the arch contract data) and a new behavior available on demand for this last version of the migration tool (migrating the arch contract data).
But I don't see it in this document. Do we explain that somewhere?

2019-07-30 08:48 UTC, merged