Update variables.md
bonitasoft/bonita-doc pull request #990
Opened 2019-10-03 09:24 UTC by DumitruCorini

- Corrected grammar mistakes
- Removed some phrases that repeat what was said in previous phrases or contradictions like "String and JSON are initialization types." (We said before that they were static type variables, not initialization type variables)
- Refactor some of the phrases

2019-10-04 13:11 UTC, educhastenier commented on md/variables.md
> +**Variables** are a key concept in the UI Designer. They define how pages, layouts, forms and fragments behave. They are used to fetch external resources, to manipulate and process information, and m
:warning: The description is missing

2019-10-04 13:12 UTC, educhastenier commented on md/variables.md
> +Create two input widgets "First name" and "Last name" and bind the values to two variables `firstname` and `lastname`.Add a text widget "Login" to display the result of the `login` expression. When t
```suggestion
Create two input widgets "First name" and "Last name" and bind the values to two variables `firstname` and `lastname` .Add a text widget "Login" to display the result of the `login` expression. When the user fills out the two input fields, the expression is updated. If the login value is manually edited before the user fills out the fields, then its value is overwritten.
```

2019-10-04 13:14 UTC, educhastenier commented on md/variables.md
>  # Variables
```suggestion
# Variables in the UI Designer
```

2019-10-04 13:14 UTC, educhastenier requested changes
The goal of the initiative is to add a description

2019-10-07 12:11 UTC, DumitruCorini commented on md/variables.md
>  # Variables
done

2019-10-07 12:11 UTC, DumitruCorini commented on md/variables.md
> +Create two input widgets "First name" and "Last name" and bind the values to two variables `firstname` and `lastname`.Add a text widget "Login" to display the result of the `login` expression. When t
done

2019-10-07 12:12 UTC, DumitruCorini commented on md/variables.md
> +**Variables** are a key concept in the UI Designer. They define how pages, layouts, forms and fragments behave. They are used to fetch external resources, to manipulate and process information, and m
Added a description

2019-10-16 13:03 UTC, educhastenier approved these changes

2019-10-16 13:04 UTC, merged